"""
Task 2 - Feature Engineering Pipeline Runner
==============================================

Production-oriented orchestration script for the predictive-maintenance
feature-engineering pipeline.

This version keeps the original runner workflow but fixes the integration
points with the project's current modules:

1. Feature engineering:
   - Uses PredictiveMaintenanceFeatureEngineer from src.feature_engineering.
   - Does not pass unsupported include_context/include_target arguments.

2. Visualization:
   - src.visualization.py currently exposes the module-level
     generate_task2_visualizations() function, not a FeatureVisualization
     class.
   - Figures are written to reports/figures/demo by default.
   - Generated PNG files are explicitly verified after visualization.

3. Reporting:
   - src.report_generator.py currently exposes ReportConfig and
     generate_all_reports(), not a ReportGenerator class.
   - Reports are written to reports/demo.
   - The report generator receives the exact generated figure mapping so the
     images are available to both HTML and DOCX reports.

Important AI4I consideration
-----------------------------
The UCI AI4I 2020 dataset contains a UID column, but UID is an identifier,
not a real machine timestamp. This runner therefore does NOT manufacture
timestamps or chronological lag/rolling features from UID.

If a real timestamp + machine_id schema is supplied to the feature-engineering
pipeline, temporal features can be generated by src/feature_engineering.py.

Expected project structure
--------------------------
predictive_maintenance_project/
│
├── data/
│   ├── raw/
│   │   └── ai4i2020.csv
│   │
│   └── processed/
│       ├── engineered_features.csv
│       ├── train_features.csv
│       ├── validation_features.csv
│       └── test_features.csv
│
├── reports/
│   ├── figures/
│   │   └── demo/
│   │       ├── 01_failure_rate.png
│   │       ├── 02_feature_distributions.png
│   │       ├── 03_correlation_heatmap.png
│   │       ├── 04_temperature_gap.png
│   │       ├── 05_mechanical_power.png
│   │       ├── 06_rolling_statistics.png
│   │       ├── 07_feature_boxplots.png
│   │       ├── 08_missing_value_profile.png
│   │       └── 09_torque_nm_vs_rotational_speed_rpm.png
│   │
│   └── demo/
│       ├── predictive_maintenance_report.html
│       ├── predictive_maintenance_report.docx
│       └── report_manifest.json
│
├── scripts/
│   └── run_task2.py
│
└── src/
    ├── config.py
    ├── data_loader.py
    ├── feature_engineering.py
    ├── feature_quality.py
    ├── visualization.py
    ├── report_generator.py
    └── realtime_features.py

Usage
-----
From the project root:

    python scripts/run_task2.py

Optional:

    python scripts/run_task2.py --raw-data data/raw/ai4i2020.csv

    python scripts/run_task2.py --skip-reports

    python scripts/run_task2.py --skip-visualizations

Exit codes
----------
0 = successful execution
1 = pipeline/data/configuration error
2 = unexpected runtime error
"""

from __future__ import annotations

import argparse
import importlib
import json
import logging
import sys
import time
import traceback
from dataclasses import asdict, is_dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Make the project root importable when this script is executed directly.
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Project imports
#
# These are deliberately defensive. The current project versions expose:
#
#   feature_engineering.py
#       PredictiveMaintenanceFeatureEngineer
#
#   visualization.py
#       generate_task2_visualizations
#
#   report_generator.py
#       ReportConfig
#       generate_all_reports
#       build_default_figure_mapping
#
# ---------------------------------------------------------------------------

DataLoader = None
PredictiveMaintenanceFeatureEngineer = None
FeatureQualityAnalyzer = None

generate_task2_visualizations = None

ReportMetadata = None
ReportConfig = None
generate_all_reports = None
save_report_manifest = None
build_default_figure_mapping = None


def _load_project_components() -> None:
    """
    Import project components using their actual public APIs.

    Import failures are stored and reported by the individual pipeline
    stages instead of making an optional reporting/visualization module
    prevent the core feature-engineering pipeline from starting.
    """
    global DataLoader
    global PredictiveMaintenanceFeatureEngineer
    global FeatureQualityAnalyzer
    global generate_task2_visualizations
    global ReportMetadata
    global ReportConfig
    global generate_all_reports
    global save_report_manifest
    global build_default_figure_mapping

    try:
        module = importlib.import_module("src.data_loader")
        DataLoader = getattr(module, "DataLoader", None)
    except Exception as exc:
        logging.getLogger("task2_pipeline").warning(
            "src.data_loader could not be imported: %s",
            exc,
        )

    try:
        module = importlib.import_module("src.feature_engineering")

        # Current implementation.
        PredictiveMaintenanceFeatureEngineer = getattr(
            module,
            "PredictiveMaintenanceFeatureEngineer",
            None,
        )

        # Backward-compatible fallback if a future/older project exposes
        # FeatureEngineer instead.
        if PredictiveMaintenanceFeatureEngineer is None:
            PredictiveMaintenanceFeatureEngineer = getattr(
                module,
                "FeatureEngineer",
                None,
            )

    except Exception as exc:
        logging.getLogger("task2_pipeline").error(
            "src.feature_engineering could not be imported: %s",
            exc,
        )

    try:
        module = importlib.import_module("src.feature_quality")
        FeatureQualityAnalyzer = getattr(
            module,
            "FeatureQualityAnalyzer",
            None,
        )

        if FeatureQualityAnalyzer is None:
            FeatureQualityAnalyzer = getattr(
                module,
                "FeatureQuality",
                None,
            )

    except Exception as exc:
        logging.getLogger("task2_pipeline").warning(
            "src.feature_quality could not be imported: %s",
            exc,
        )

    try:
        module = importlib.import_module("src.visualization")

        # IMPORTANT:
        # The current visualization.py does NOT expose a
        # FeatureVisualization class. It exposes this function.
        generate_task2_visualizations = getattr(
            module,
            "generate_task2_visualizations",
            None,
        )

    except Exception as exc:
        logging.getLogger("task2_pipeline").error(
            "src.visualization could not be imported: %s",
            exc,
        )

    try:
        module = importlib.import_module("src.report_generator")

        ReportMetadata = getattr(
            module,
            "ReportMetadata",
            None,
        )

        ReportConfig = getattr(
            module,
            "ReportConfig",
            None,
        )

        generate_all_reports = getattr(
            module,
            "generate_all_reports",
            None,
        )

        save_report_manifest = getattr(
            module,
            "save_report_manifest",
            None,
        )

        build_default_figure_mapping = getattr(
            module,
            "build_default_figure_mapping",
            None,
        )

    except Exception as exc:
        logging.getLogger("task2_pipeline").warning(
            "src.report_generator could not be imported: %s",
            exc,
        )


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_RAW_DATA = PROJECT_ROOT / "data" / "raw" / "ai4i2020.csv"

DEFAULT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

DEFAULT_REPORT_DIR = PROJECT_ROOT / "reports" / "demo"

# IMPORTANT:
# visualization.py and report_generator.py use this directory.
DEFAULT_FIGURE_DIR = PROJECT_ROOT / "reports" / "figures" / "demo"

DEFAULT_TRAIN_SIZE = 0.70
DEFAULT_VALIDATION_SIZE = 0.15
DEFAULT_TEST_SIZE = 0.15
DEFAULT_RANDOM_STATE = 42

TARGET_COLUMN_CANDIDATES = (
    "machine_failure",
    "Machine failure",
    "target",
    "Target",
    "failure",
)

ID_COLUMNS = (
    "uid",
    "UID",
    "product_id",
    "Product ID",
    "machine_id",
    "Machine ID",
)

LEAKAGE_COLUMNS = (
    "twf",
    "hdf",
    "pwf",
    "osf",
    "rnf",
    "TWF",
    "HDF",
    "PWF",
    "OSF",
    "RNF",
    "failure_type",
    "Failure Type",
)

EXPECTED_AI4I_ROWS = 10_000

LOGGER = logging.getLogger("task2_pipeline")


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def configure_logging(verbose: bool = False) -> None:
    """Configure application-wide logging."""
    level = logging.DEBUG if verbose else logging.INFO

    logging.basicConfig(
        level=level,
        format=(
            "%(asctime)s | "
            "%(levelname)-8s | "
            "%(name)s | "
            "%(message)s"
        ),
        datefmt="%Y-%m-%d %H:%M:%S",
        force=True,
    )


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def utc_now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).isoformat()


def ensure_directory(path: Path) -> Path:
    """Create a directory if it does not already exist."""
    path.mkdir(parents=True, exist_ok=True)
    return path


def safe_json_value(value: Any) -> Any:
    """Convert common NumPy/Pandas/dataclass values into JSON-safe objects."""
    if value is None:
        return None

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        if np.isnan(value):
            return None
        return float(value)

    if isinstance(value, (np.bool_,)):
        return bool(value)

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, pd.Series):
        return value.tolist()

    if isinstance(value, pd.DataFrame):
        return value.to_dict(orient="records")

    if is_dataclass(value):
        return {
            key: safe_json_value(val)
            for key, val in asdict(value).items()
        }

    if isinstance(value, Mapping):
        return {
            str(key): safe_json_value(val)
            for key, val in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        return [safe_json_value(item) for item in value]

    return value


def write_json(
    data: Dict[str, Any],
    output_path: Path,
) -> None:
    """Write a dictionary to a formatted JSON file."""
    ensure_directory(output_path.parent)

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            safe_json_value(data),
            file,
            indent=2,
            ensure_ascii=False,
        )


def find_column(
    df: pd.DataFrame,
    candidates: Sequence[str],
) -> Optional[str]:
    """
    Find the first matching column from a list of candidates.

    Matching is case-sensitive first, followed by normalized
    case-insensitive comparison.
    """
    for candidate in candidates:
        if candidate in df.columns:
            return candidate

    normalized = {
        str(column).strip().lower(): column
        for column in df.columns
    }

    for candidate in candidates:
        key = str(candidate).strip().lower()

        if key in normalized:
            return normalized[key]

    return None


def normalize_column_names(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Normalize known AI4I column names.

    The transformation is intentionally conservative.
    """
    result = df.copy()

    known_mappings = {
        "UID": "uid",
        "Product ID": "product_id",
        "Type": "type",
        "Air temperature [K]": "air_temperature_k",
        "Process temperature [K]": "process_temperature_k",
        "Rotational speed [rpm]": "rotational_speed_rpm",
        "Torque [Nm]": "torque_nm",
        "Tool wear [min]": "tool_wear_min",
        "Machine failure": "machine_failure",
        "TWF": "twf",
        "HDF": "hdf",
        "PWF": "pwf",
        "OSF": "osf",
        "RNF": "rnf",
        "Failure Type": "failure_type",
    }

    rename_map = {
        original: normalized
        for original, normalized in known_mappings.items()
        if original in result.columns
    }

    if rename_map:
        result = result.rename(columns=rename_map)

    return result


def validate_split_sizes(
    train_size: float,
    validation_size: float,
    test_size: float,
) -> None:
    """Validate train/validation/test proportions."""
    sizes = (
        train_size,
        validation_size,
        test_size,
    )

    if any(size <= 0 or size >= 1 for size in sizes):
        raise ValueError(
            "Train, validation, and test sizes must each be greater than "
            "0 and less than 1."
        )

    total = sum(sizes)

    if not np.isclose(total, 1.0, atol=1e-8):
        raise ValueError(
            "Train, validation, and test sizes must sum to 1.0. "
            f"Received {total:.6f}."
        )


def validate_dataframe(
    df: pd.DataFrame,
    require_target: bool = True,
) -> str:
    """
    Validate the loaded dataset.

    Returns
    -------
    str
        Detected target column.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Expected a pandas DataFrame.")

    if df.empty:
        raise ValueError("The input dataset is empty.")

    if df.shape[1] < 2:
        raise ValueError(
            "The input dataset must contain at least two columns."
        )

    duplicated_columns = df.columns[
        df.columns.duplicated()
    ].tolist()

    if duplicated_columns:
        raise ValueError(
            "Duplicate column names detected: "
            f"{duplicated_columns}"
        )

    target_column = find_column(
        df,
        TARGET_COLUMN_CANDIDATES,
    )

    if require_target and target_column is None:
        raise ValueError(
            "Could not identify the target column. Expected one of: "
            f"{TARGET_COLUMN_CANDIDATES}"
        )

    if target_column is not None:
        target_values = df[target_column].dropna()

        if target_values.empty:
            raise ValueError(
                f"Target column '{target_column}' contains only missing values."
            )

        if target_values.nunique() < 2:
            raise ValueError(
                f"Target column '{target_column}' contains fewer than "
                "two unique values."
            )

    return target_column or ""


def detect_ai4i_schema(
    df: pd.DataFrame,
) -> Dict[str, Any]:
    """Detect whether supplied data follows the AI4I-style schema."""
    required_ai4i_columns = {
        "uid",
        "product_id",
        "type",
        "air_temperature_k",
        "process_temperature_k",
        "rotational_speed_rpm",
        "torque_nm",
        "tool_wear_min",
        "machine_failure",
    }

    present = set(df.columns)
    matched = required_ai4i_columns.intersection(present)

    return {
        "is_ai4i_like": len(matched) >= 7,
        "matched_ai4i_columns": sorted(matched),
        "matched_count": len(matched),
        "expected_count": len(required_ai4i_columns),
    }


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_raw_data(
    raw_data_path: Path,
) -> pd.DataFrame:
    """
    Load the raw CSV dataset.

    The project's DataLoader is preferred when a compatible public method
    exists. pandas.read_csv() is the reliable fallback.
    """
    if not raw_data_path.exists():
        raise FileNotFoundError(
            f"Raw dataset was not found: {raw_data_path}"
        )

    if raw_data_path.suffix.lower() != ".csv":
        raise ValueError(
            "This Task 2 runner currently expects a CSV input file."
        )

    LOGGER.info(
        "Loading raw dataset from: %s",
        raw_data_path,
    )

    if DataLoader is not None:
        try:
            loader = DataLoader()

            candidate_methods = (
                "load_csv",
                "load_data",
                "load",
                "read_csv",
            )

            for method_name in candidate_methods:
                method = getattr(
                    loader,
                    method_name,
                    None,
                )

                if method is None:
                    continue

                try:
                    loaded = method(raw_data_path)
                except TypeError:
                    loaded = method(str(raw_data_path))

                if isinstance(loaded, pd.DataFrame):
                    LOGGER.info(
                        "Dataset loaded using src.data_loader.%s().",
                        method_name,
                    )
                    return loaded

        except Exception as exc:
            LOGGER.warning(
                "Project DataLoader could not be used: %s. "
                "Falling back to pandas.read_csv().",
                exc,
            )

    df = pd.read_csv(raw_data_path)

    LOGGER.info(
        "Dataset loaded using pandas.read_csv()."
    )

    return df


# ---------------------------------------------------------------------------
# Dataset splitting
# ---------------------------------------------------------------------------

def stratified_split(
    df: pd.DataFrame,
    target_column: str,
    train_size: float,
    validation_size: float,
    test_size: float,
    random_state: int,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Create a reproducible stratified train/validation/test split.
    """
    validate_split_sizes(
        train_size,
        validation_size,
        test_size,
    )

    try:
        from sklearn.model_selection import train_test_split
    except ImportError as exc:
        raise ImportError(
            "scikit-learn is required for train/validation/test splitting."
        ) from exc

    if target_column not in df.columns:
        raise KeyError(
            f"Target column '{target_column}' not found."
        )

    y = df[target_column]

    if y.isna().any():
        raise ValueError(
            "The target contains missing values. "
            "Clean the target before creating supervised-learning splits."
        )

    class_counts = y.value_counts()

    if len(class_counts) < 2:
        raise ValueError(
            "The target must contain at least two classes."
        )

    if class_counts.min() < 3:
        raise ValueError(
            "Stratified train/validation/test splitting requires at least "
            "3 observations in every target class. "
            f"Class counts: {class_counts.to_dict()}"
        )

    train_val_df, test_df = train_test_split(
        df,
        test_size=test_size,
        random_state=random_state,
        stratify=y,
    )

    relative_validation_size = validation_size / (
        train_size + validation_size
    )

    train_df, validation_df = train_test_split(
        train_val_df,
        test_size=relative_validation_size,
        random_state=random_state,
        stratify=train_val_df[target_column],
    )

    train_df = train_df.sort_index()
    validation_df = validation_df.sort_index()
    test_df = test_df.sort_index()

    return (
        train_df.reset_index(drop=True),
        validation_df.reset_index(drop=True),
        test_df.reset_index(drop=True),
    )


def summarize_split(
    df: pd.DataFrame,
    target_column: str,
) -> Dict[str, Any]:
    """Produce a concise summary for one data partition."""
    summary: Dict[str, Any] = {
        "rows": int(len(df)),
        "columns": int(df.shape[1]),
        "missing_cells": int(df.isna().sum().sum()),
        "missing_rate": float(df.isna().mean().mean()),
    }

    if target_column in df.columns:
        distribution = (
            df[target_column]
            .value_counts(dropna=False)
            .sort_index()
        )

        summary["target_distribution"] = {
            str(key): int(value)
            for key, value in distribution.items()
        }

        if len(df) > 0:
            positive_count = 0

            for key, value in distribution.items():
                is_positive = (
                    key == 1
                    or key is True
                    or str(key).strip().lower() in {
                        "1",
                        "true",
                        "yes",
                        "failure",
                    }
                )

                if is_positive:
                    positive_count += int(value)

            summary["positive_rate"] = float(
                positive_count / len(df)
            )

    return summary


# ---------------------------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------------------------

def build_feature_engineer(
    random_state: int,
) -> Any:
    """
    Build the current project's feature engineer.

    The current feature_engineering.py uses
    PredictiveMaintenanceFeatureEngineer directly. It does not use the
    FeatureEngineeringConfig interface assumed by the previous runner.

    random_state is retained in the runner API for reproducibility of the
    overall pipeline; the current feature engineer itself does not require
    a random_state constructor argument.
    """
    del random_state

    if PredictiveMaintenanceFeatureEngineer is None:
        raise ImportError(
            "Could not import PredictiveMaintenanceFeatureEngineer from "
            "src.feature_engineering."
        )

    # The current class accepts these parameters. We explicitly preserve
    # identifiers because the generated datasets should remain traceable.
    try:
        engineer = PredictiveMaintenanceFeatureEngineer(
            add_missing_indicators=True,
            keep_identifiers=True,
        )
    except TypeError:
        # Compatibility fallback for a simpler implementation.
        engineer = PredictiveMaintenanceFeatureEngineer()

    return engineer


def fit_transform_features(
    engineer: Any,
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Fit feature engineering on training data and transform all partitions.

    IMPORTANT:
    The current FeatureEngineer.transform() accepts only the DataFrame.
    The previous runner incorrectly supplied include_context/include_target,
    which caused an API mismatch. This function now uses the real API.
    """
    LOGGER.info(
        "Fitting feature-engineering transformations on training data only."
    )

    if not hasattr(engineer, "fit"):
        raise AttributeError(
            "Feature engineer must provide a fit() method."
        )

    engineer.fit(train_df)

    if not hasattr(engineer, "transform"):
        raise AttributeError(
            "Feature engineer must provide a transform() method."
        )

    LOGGER.info("Transforming training partition.")
    train_features = engineer.transform(train_df)

    LOGGER.info("Transforming validation partition.")
    validation_features = engineer.transform(validation_df)

    LOGGER.info("Transforming test partition.")
    test_features = engineer.transform(test_df)

    return (
        train_features,
        validation_features,
        test_features,
    )


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

def export_dataframe(
    df: pd.DataFrame,
    path: Path,
) -> None:
    """Export a DataFrame to CSV."""
    ensure_directory(path.parent)

    df.to_csv(
        path,
        index=False,
        encoding="utf-8",
    )

    LOGGER.info(
        "Exported %d rows × %d columns -> %s",
        len(df),
        df.shape[1],
        path,
    )


# ---------------------------------------------------------------------------
# Feature-quality analysis
# ---------------------------------------------------------------------------

def run_feature_quality_analysis(
    train_features: pd.DataFrame,
    output_dir: Path,
) -> Dict[str, Any]:
    """
    Execute feature-quality analysis when the optional analyzer exists.

    The quality stage is downstream of the core pipeline. If its API is
    different, the main datasets and visualizations are still preserved.
    """
    result: Dict[str, Any] = {
        "status": "skipped",
        "reason": None,
    }

    if FeatureQualityAnalyzer is None:
        result["reason"] = (
            "FeatureQualityAnalyzer is unavailable or src.feature_quality "
            "could not be imported."
        )
        LOGGER.warning(result["reason"])
        return result

    ensure_directory(output_dir)

    try:
        analyzer = FeatureQualityAnalyzer()
    except Exception as exc:
        result["status"] = "failed"
        result["reason"] = str(exc)
        LOGGER.exception(
            "Could not initialize FeatureQualityAnalyzer."
        )
        return result

    candidate_methods = (
        "analyze",
        "generate_quality_report",
        "run",
        "fit_transform",
    )

    for method_name in candidate_methods:
        method = getattr(
            analyzer,
            method_name,
            None,
        )

        if method is None:
            continue

        try:
            analysis = method(train_features)

            if isinstance(analysis, pd.DataFrame):
                quality_path = (
                    output_dir
                    / "feature_quality_report.csv"
                )

                analysis.to_csv(
                    quality_path,
                    index=False,
                    encoding="utf-8",
                )

                result.update(
                    {
                        "status": "completed",
                        "method": method_name,
                        "output": str(quality_path),
                    }
                )

            elif analysis is not None:
                result.update(
                    {
                        "status": "completed",
                        "method": method_name,
                        "result_type": type(analysis).__name__,
                    }
                )

            else:
                result.update(
                    {
                        "status": "completed",
                        "method": method_name,
                    }
                )

            LOGGER.info(
                "Feature-quality analysis completed using %s().",
                method_name,
            )

            return result

        except TypeError:
            continue

        except Exception as exc:
            result["status"] = "failed"
            result["reason"] = str(exc)

            LOGGER.exception(
                "Feature-quality method %s() failed.",
                method_name,
            )

            return result

    result["reason"] = (
        "No compatible public feature-quality method was found."
    )

    LOGGER.warning(result["reason"])

    return result


# ---------------------------------------------------------------------------
# Visualization
# ---------------------------------------------------------------------------

EXPECTED_FIGURE_FILES = (
    "01_failure_rate.png",
    "02_feature_distributions.png",
    "03_correlation_heatmap.png",
    "04_temperature_gap.png",
    "05_mechanical_power.png",
    "06_rolling_statistics.png",
    "07_feature_boxplots.png",
    "08_missing_value_profile.png",
    "09_torque_nm_vs_rotational_speed_rpm.png",
)


def collect_generated_figures(
    output_dir: Path,
) -> Dict[str, Path]:
    """
    Discover the standard generated Task 2 figures.

    The returned mapping uses the same titles expected by report_generator.
    Only existing files are returned.
    """
    title_by_filename = {
        "01_failure_rate.png": "Failure Rate",
        "02_feature_distributions.png": "Feature Distributions",
        "03_correlation_heatmap.png": "Correlation Heatmap",
        "04_temperature_gap.png": "Temperature Gap",
        "05_mechanical_power.png": "Mechanical Power",
        "06_rolling_statistics.png": "Rolling Statistics",
        "07_feature_boxplots.png": "Feature Boxplots",
        "08_missing_value_profile.png": "Missing Value Profile",
        "09_torque_nm_vs_rotational_speed_rpm.png": (
            "Torque vs Rotational Speed"
        ),
    }

    result: Dict[str, Path] = {}

    for filename, title in title_by_filename.items():
        path = output_dir / filename

        if path.is_file() and path.stat().st_size > 0:
            result[title] = path

    return result


def run_visualizations(
    train_features: pd.DataFrame,
    output_dir: Path,
    target_column: str,
) -> Dict[str, Any]:
    """
    Generate Task 2 visualizations using the actual public API.

    The current visualization module exposes:
        generate_task2_visualizations(...)

    It does NOT expose:
        FeatureVisualization(...)

    This distinction was the primary reason the previous runner did not
    generate images.
    """
    result: Dict[str, Any] = {
        "status": "skipped",
        "reason": None,
        "generated": {},
        "output_directory": str(output_dir),
    }

    if generate_task2_visualizations is None:
        result["status"] = "failed"
        result["reason"] = (
            "src.visualization.generate_task2_visualizations could not "
            "be imported."
        )
        LOGGER.error(result["reason"])
        return result

    ensure_directory(output_dir)

    # A real timestamp/machine_id is deliberately not invented for AI4I.
    timestamp_column = (
        "timestamp"
        if "timestamp" in train_features.columns
        else None
    )

    machine_id_column = None

    for candidate in (
        "machine_id",
        "Machine ID",
    ):
        if candidate in train_features.columns:
            machine_id_column = candidate
            break

    try:
        generated = generate_task2_visualizations(
            train_features,
            output_directory=output_dir,
            target_column=target_column,
            timestamp_column=timestamp_column,
            machine_id_column=machine_id_column,
        )

        if generated is None:
            generated = {}

        generated_paths = {
            str(name): str(Path(path))
            for name, path in dict(generated).items()
        }

        # Explicitly verify the actual files on disk. This prevents a
        # "completed" status when a plotting function returns a path that
        # was not successfully written.
        existing = collect_generated_figures(output_dir)

        result.update(
            {
                "status": "completed" if existing else "failed",
                "generated": generated_paths,
                "verified_files": {
                    title: str(path)
                    for title, path in existing.items()
                },
                "count": len(existing),
            }
        )

        if existing:
            LOGGER.info(
                "Visualization generation completed: %d PNG files found.",
                len(existing),
            )

            for title, path in existing.items():
                LOGGER.info(
                    "  IMAGE OK: %s -> %s",
                    title,
                    path,
                )

        else:
            result["reason"] = (
                "Visualization function completed but no PNG files were "
                f"found in {output_dir}."
            )

            LOGGER.error(result["reason"])

        return result

    except Exception as exc:
        result["status"] = "failed"
        result["reason"] = str(exc)

        LOGGER.exception(
            "Task 2 visualization generation failed."
        )

        return result


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

def run_report_generation(
    dataset: pd.DataFrame,
    report_dir: Path,
    figure_dir: Path,
    metadata: Dict[str, Any],
    figure_mapping: Optional[Mapping[str, Path]] = None,
    train_shape: Optional[Tuple[int, int]] = None,
    validation_shape: Optional[Tuple[int, int]] = None,
    test_shape: Optional[Tuple[int, int]] = None,
) -> Dict[str, Any]:
    """
    Generate HTML/DOCX reports using the current report_generator API.

    The current report generator expects:
        ReportMetadata
        ReportConfig
        generate_all_reports(dataset=..., ...)
    """
    result: Dict[str, Any] = {
        "status": "skipped",
        "reason": None,
        "html": None,
        "docx": None,
        "manifest": None,
        "figures": [],
    }

    if ReportConfig is None or generate_all_reports is None:
        result["status"] = "failed"
        result["reason"] = (
            "src.report_generator.ReportConfig or "
            "generate_all_reports is unavailable."
        )
        LOGGER.error(result["reason"])
        return result

    ensure_directory(report_dir)
    ensure_directory(figure_dir)

    if figure_mapping is None:
        if build_default_figure_mapping is not None:
            figure_mapping = build_default_figure_mapping(figure_dir)
        else:
            figure_mapping = {
                "Failure Rate": figure_dir / "01_failure_rate.png",
                "Feature Distributions": figure_dir / "02_feature_distributions.png",
                "Correlation Heatmap": figure_dir / "03_correlation_heatmap.png",
                "Temperature Gap": figure_dir / "04_temperature_gap.png",
                "Mechanical Power": figure_dir / "05_mechanical_power.png",
                "Rolling Statistics": figure_dir / "06_rolling_statistics.png",
                "Feature Boxplots": figure_dir / "07_feature_boxplots.png",
                "Missing Value Profile": figure_dir / "08_missing_value_profile.png",
                "Torque vs Rotational Speed": figure_dir / "09_torque_nm_vs_rotational_speed_rpm.png",
            }

    figure_mapping = {
        str(title): Path(path)
        for title, path in figure_mapping.items()
    }

    existing_figures = {
        title: path
        for title, path in figure_mapping.items()
        if path.is_file() and path.stat().st_size > 0
    }

    LOGGER.info(
        "Report stage sees %d existing figure files in %s.",
        len(existing_figures),
        figure_dir,
    )

    try:
        if ReportMetadata is not None:
            report_meta = ReportMetadata(
                execution_timestamp=utc_now_iso(),
                target_column=str(
                    metadata.get("target", {}).get(
                        "column", "machine_failure"
                    )
                ),
                timestamp_column=None,
                machine_id_column=None,
                notes=[
                    "Generated by Task 2 feature-engineering pipeline.",
                    "UID is treated as an identifier, not as a timestamp.",
                    "Known AI4I failure-mode labels are excluded from predictive features.",
                    f"Verified visualization files: {len(existing_figures)}.",
                ],
            )
        else:
            report_meta = None

        config = ReportConfig(
            output_directory=report_dir,
            figures_directory=figure_dir,
            include_embedded_images=True,
            include_source_links=True,
            generate_docx=True,
            overwrite_existing=True,
        )

        generated = generate_all_reports(
            metadata=report_meta,
            config=config,
            dataset=dataset,
            figures=figure_mapping,
            train_shape=train_shape,
            validation_shape=validation_shape,
            test_shape=test_shape,
            engineered_features=list(dataset.columns),
            methodology_notes=(
                "Feature engineering is fitted on the training partition "
                "and applied to validation/test partitions. "
                "AI4I UID is not interpreted as time."
            ),
            leakage_notes=(
                "Target and known failure-mode labels are retained only "
                "for context/diagnostics and are removed from predictive "
                "feature exports."
            ),
            realtime_notes=(
                "Real-time temporal continuity is handled separately by "
                "realtime_features.py when a valid timestamp is available."
            ),
        )

        if isinstance(generated, Mapping):
            generated_dict = dict(generated)
        else:
            generated_dict = {}

        html_path = generated_dict.get("html")
        docx_path = generated_dict.get("docx")

        if html_path is not None:
            html_path = Path(html_path)
        if docx_path is not None:
            docx_path = Path(docx_path)

        manifest_path = None
        if save_report_manifest is not None:
            manifest_path = save_report_manifest(
                generated_dict,
                output_path=report_dir / "report_manifest.json",
                metadata=report_meta,
            )

        result.update(
            {
                "status": "completed",
                "html": str(html_path) if html_path else None,
                "docx": str(docx_path) if docx_path else None,
                "manifest": str(manifest_path) if manifest_path else None,
                "figures": [str(path) for path in existing_figures.values()],
                "figure_count": len(existing_figures),
            }
        )

        LOGGER.info(
            "Report generation completed successfully."
        )

        return result

    except Exception as exc:
        result["status"] = "failed"
        result["reason"] = str(exc)

        LOGGER.exception(
            "Report generation failed."
        )

        return result


# ---------------------------------------------------------------------------
# Leakage and integrity checks
# ---------------------------------------------------------------------------

def check_for_target_leakage(
    features: pd.DataFrame,
    target_column: str,
) -> Dict[str, Any]:
    """
    Check the full engineered frame while distinguishing context columns
    from actual predictive columns.

    The feature engineer keeps AI4I labels in the returned frame for
    traceability. Therefore the full frame may contain twf/hdf/pwf/osf/rnf;
    the predictive matrix must not.
    """
    predictive = build_predictive_feature_frame(
        features,
        target_column,
    )

    safety = assert_predictive_feature_safety(
        predictive,
        target_column,
    )

    return {
        "leakage_columns_present": safety["forbidden_columns_present"],
        "predictive_feature_count_checked": safety["feature_count"],
        "context_columns_retained": [
            column
            for column in features.columns
            if column not in predictive.columns
        ],
        "passed": safety["passed"],
    }


def check_split_disjointness(
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
    id_column: Optional[str],
) -> Dict[str, Any]:
    """
    Verify that ID values do not overlap across partitions.

    For the canonical AI4I dataset, UID is row-level and unique, so overlap
    checking is useful as an integrity check. It is not interpreted as a
    machine-time sequence.
    """
    if id_column is None:
        return {
            "checked": False,
            "reason": "No suitable ID column detected.",
            "passed": True,
        }

    if id_column not in train_df.columns:
        return {
            "checked": False,
            "reason": f"ID column '{id_column}' is not present.",
            "passed": True,
        }

    train_ids = set(
        train_df[id_column].dropna().tolist()
    )

    validation_ids = set(
        validation_df[id_column].dropna().tolist()
    )

    test_ids = set(
        test_df[id_column].dropna().tolist()
    )

    train_validation_overlap = train_ids.intersection(
        validation_ids
    )

    train_test_overlap = train_ids.intersection(
        test_ids
    )

    validation_test_overlap = validation_ids.intersection(
        test_ids
    )

    passed = not any(
        (
            train_validation_overlap,
            train_test_overlap,
            validation_test_overlap,
        )
    )

    return {
        "checked": True,
        "id_column": id_column,
        "passed": passed,
        "train_validation_overlap": len(
            train_validation_overlap
        ),
        "train_test_overlap": len(
            train_test_overlap
        ),
        "validation_test_overlap": len(
            validation_test_overlap
        ),
    }


# ---------------------------------------------------------------------------
# Pipeline metadata
# ---------------------------------------------------------------------------

def build_pipeline_metadata(
    raw_df: pd.DataFrame,
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
    train_features: pd.DataFrame,
    validation_features: pd.DataFrame,
    test_features: pd.DataFrame,
    target_column: str,
    raw_data_path: Path,
    random_state: int,
    train_size: float,
    validation_size: float,
    test_size: float,
) -> Dict[str, Any]:
    """Build a comprehensive machine-readable execution summary."""
    ai4i_schema = detect_ai4i_schema(raw_df)

    train_predictive = build_predictive_feature_frame(
        train_features,
        target_column,
    )
    validation_predictive = build_predictive_feature_frame(
        validation_features,
        target_column,
    )
    test_predictive = build_predictive_feature_frame(
        test_features,
        target_column,
    )

    id_column = find_column(
        raw_df,
        ID_COLUMNS,
    )

    leakage_check = check_for_target_leakage(
        train_features,
        target_column,
    )

    split_check = check_split_disjointness(
        train_df,
        validation_df,
        test_df,
        id_column,
    )

    metadata: Dict[str, Any] = {
        "project": "Predictive Maintenance - Task 2",
        "task": "Feature Engineering",
        "generated_at_utc": utc_now_iso(),

        "dataset": {
            "path": str(raw_data_path),
            "rows": int(len(raw_df)),
            "columns": int(raw_df.shape[1]),
            "column_names": [
                str(column)
                for column in raw_df.columns
            ],
            "ai4i_like_schema": ai4i_schema,
        },

        "split": {
            "random_state": random_state,
            "train_size": train_size,
            "validation_size": validation_size,
            "test_size": test_size,
            "train": summarize_split(
                train_df,
                target_column,
            ),
            "validation": summarize_split(
                validation_df,
                target_column,
            ),
            "test": summarize_split(
                test_df,
                target_column,
            ),
        },

        "features": {
            "train_rows": int(len(train_features)),
            "validation_rows": int(len(validation_features)),
            "test_rows": int(len(test_features)),
            "train_feature_columns": int(train_features.shape[1]),
            "validation_feature_columns": int(
                validation_features.shape[1]
            ),
            "test_feature_columns": int(test_features.shape[1]),
            "feature_names": [
                str(column)
                for column in train_features.columns
            ],
        },

        "target": {
            "column": target_column,
            "dtype": str(raw_df[target_column].dtype),
            "unique_values": [
                safe_json_value(value)
                for value in raw_df[target_column]
                .dropna()
                .unique()
            ],
        },

        "leakage_checks": {
            "target_and_failure_columns": leakage_check,
            "split_disjointness": split_check,
        },

        "design_principles": [
            "Feature transformations are fitted using training data only.",
            "Validation and test data are transformed using the fitted feature engineer.",
            "Target and known failure-mode columns are not used as predictive features.",
            "UID is treated as an identifier, not as a fabricated timestamp.",
            "Temporal features are generated only when a valid timestamp is available.",
            "Real-time stateful temporal continuity is handled by realtime_features.py.",
            "Visualization artifacts are written to reports/figures/demo.",
            "Reports are written to reports/demo.",
        ],

        "expected_ai4i_rows": EXPECTED_AI4I_ROWS,
    }

    return metadata


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_pipeline(
    raw_data_path: Path,
    processed_dir: Path,
    report_dir: Path,
    figure_dir: Path,
    train_size: float,
    validation_size: float,
    test_size: float,
    random_state: int,
    skip_visualizations: bool = False,
    skip_reports: bool = False,
) -> Dict[str, Any]:
    """
    Execute the complete Task 2 batch feature-engineering pipeline.
    """
    pipeline_start = time.perf_counter()

    LOGGER.info("=" * 78)
    LOGGER.info(
        "PREDICTIVE MAINTENANCE - TASK 2 FEATURE ENGINEERING"
    )
    LOGGER.info("=" * 78)

    ensure_directory(processed_dir)
    ensure_directory(report_dir)
    ensure_directory(figure_dir)

    # ------------------------------------------------------------------
    # Step 1: Load raw data
    # ------------------------------------------------------------------

    LOGGER.info("[1/9] Loading raw dataset.")

    raw_df = load_raw_data(
        raw_data_path
    )

    LOGGER.info(
        "Raw dataset shape: %s",
        raw_df.shape,
    )

    raw_df = normalize_column_names(
        raw_df
    )

    target_column = validate_dataframe(
        raw_df,
        require_target=True,
    )

    LOGGER.info(
        "Detected target column: %s",
        target_column,
    )

    # ------------------------------------------------------------------
    # Step 2: Dataset diagnostics
    # ------------------------------------------------------------------

    LOGGER.info("[2/9] Running dataset diagnostics.")

    schema = detect_ai4i_schema(raw_df)

    if schema["is_ai4i_like"]:
        LOGGER.info(
            "AI4I-style schema detected (%d/%d canonical columns).",
            schema["matched_count"],
            schema["expected_count"],
        )

        if len(raw_df) != EXPECTED_AI4I_ROWS:
            LOGGER.warning(
                "AI4I-style dataset contains %d rows; the canonical "
                "AI4I 2020 dataset contains %d rows.",
                len(raw_df),
                EXPECTED_AI4I_ROWS,
            )

    # ------------------------------------------------------------------
    # Step 3: Dataset split
    # ------------------------------------------------------------------

    LOGGER.info(
        "[3/9] Creating train/validation/test partitions."
    )

    train_df, validation_df, test_df = stratified_split(
        df=raw_df,
        target_column=target_column,
        train_size=train_size,
        validation_size=validation_size,
        test_size=test_size,
        random_state=random_state,
    )

    LOGGER.info(
        "Train shape:      %s",
        train_df.shape,
    )

    LOGGER.info(
        "Validation shape: %s",
        validation_df.shape,
    )

    LOGGER.info(
        "Test shape:       %s",
        test_df.shape,
    )

    # ------------------------------------------------------------------
    # Step 4: Feature engineering
    # ------------------------------------------------------------------

    LOGGER.info(
        "[4/9] Performing leakage-safe feature engineering."
    )

    engineer = build_feature_engineer(
        random_state=random_state
    )

    (
        train_features,
        validation_features,
        test_features,
    ) = fit_transform_features(
        engineer=engineer,
        train_df=train_df,
        validation_df=validation_df,
        test_df=test_df,
    )

    LOGGER.info(
        "Engineered train shape:      %s",
        train_features.shape,
    )

    LOGGER.info(
        "Engineered validation shape: %s",
        validation_features.shape,
    )

    LOGGER.info(
        "Engineered test shape:       %s",
        test_features.shape,
    )

    # ------------------------------------------------------------------
    # Step 5: Feature consistency
    # ------------------------------------------------------------------

    LOGGER.info(
        "[5/9] Validating feature consistency."
    )

    train_feature_names = list(train_features.columns)
    validation_feature_names = list(validation_features.columns)
    test_feature_names = list(test_features.columns)

    if train_feature_names != validation_feature_names:
        raise ValueError(
            "Train and validation feature schemas do not match."
        )

    if train_feature_names != test_feature_names:
        raise ValueError(
            "Train and test feature schemas do not match."
        )

    LOGGER.info(
        "Feature schema consistency check passed."
    )

    # ------------------------------------------------------------------
    # Step 6: Leakage checks
    # ------------------------------------------------------------------

    LOGGER.info(
        "[6/9] Running leakage and integrity checks."
    )

    leakage_check = check_for_target_leakage(
        train_features,
        target_column,
    )

    # The feature engineer intentionally returns context columns such as
    # twf/hdf/pwf/osf/rnf. They are NOT model predictors. Build separate
    # leakage-safe predictive matrices for downstream ML/export.
    train_predictive = build_predictive_feature_frame(
        train_features,
        target_column,
    )
    validation_predictive = build_predictive_feature_frame(
        validation_features,
        target_column,
    )
    test_predictive = build_predictive_feature_frame(
        test_features,
        target_column,
    )

    train_safety = assert_predictive_feature_safety(
        train_predictive,
        target_column,
    )
    validation_safety = assert_predictive_feature_safety(
        validation_predictive,
        target_column,
    )
    test_safety = assert_predictive_feature_safety(
        test_predictive,
        target_column,
    )

    if not (
        train_safety["passed"]
        and validation_safety["passed"]
        and test_safety["passed"]
    ):
        raise RuntimeError(
            "Predictive feature leakage detected after sanitization: "
            f"train={train_safety['forbidden_columns_present']}, "
            f"validation={validation_safety['forbidden_columns_present']}, "
            f"test={test_safety['forbidden_columns_present']}"
        )

    if list(train_predictive.columns) != list(validation_predictive.columns):
        raise ValueError(
            "Train and validation predictive feature schemas do not match."
        )

    if list(train_predictive.columns) != list(test_predictive.columns):
        raise ValueError(
            "Train and test predictive feature schemas do not match."
        )

    id_column = find_column(
        raw_df,
        ID_COLUMNS,
    )

    split_check = check_split_disjointness(
        train_df,
        validation_df,
        test_df,
        id_column,
    )

    if not split_check["passed"]:
        LOGGER.warning(
            "ID overlap was detected across data partitions."
        )

    LOGGER.info(
        "Leakage-safe predictive feature check passed: %d features.",
        train_predictive.shape[1],
    )
    # ------------------------------------------------------------------
    # Step 7: Export processed datasets
    # ------------------------------------------------------------------

    LOGGER.info(
        "[7/9] Exporting leakage-safe engineered datasets."
    )

    engineered_path = processed_dir / "engineered_features.csv"
    train_path = processed_dir / "train_features.csv"
    validation_path = processed_dir / "validation_features.csv"
    test_path = processed_dir / "test_features.csv"

    engineered_df = pd.concat(
        [
            train_predictive,
            validation_predictive,
            test_predictive,
        ],
        axis=0,
        ignore_index=True,
    )

    export_dataframe(engineered_df, engineered_path)
    export_dataframe(train_predictive, train_path)
    export_dataframe(validation_predictive, validation_path)
    export_dataframe(test_predictive, test_path)

    # Preserve a context copy for reporting/diagnostics without mixing those
    # labels into the model-ready files.
    context_dir = ensure_directory(
        processed_dir / "context"
    )

    export_dataframe(
        pd.concat(
            [train_features, validation_features, test_features],
            axis=0,
            ignore_index=True,
        ),
        context_dir / "engineered_features_with_context.csv",
    )
    export_dataframe(
        train_features,
        context_dir / "train_features_with_context.csv",
    )
    export_dataframe(
        validation_features,
        context_dir / "validation_features_with_context.csv",
    )
    export_dataframe(
        test_features,
        context_dir / "test_features_with_context.csv",
    )
    # ------------------------------------------------------------------
    # Step 8: Quality, visualizations, and reports
    # ------------------------------------------------------------------

    LOGGER.info(
        "[8/9] Generating quality artifacts, visualizations, and reports."
    )

    quality_result = run_feature_quality_analysis(
        train_features=train_predictive,
        output_dir=report_dir,
    )

    if skip_visualizations:
        visualization_result = {
            "status": "skipped",
            "reason": "Disabled by --skip-visualizations.",
            "generated": {},
            "verified_files": {},
            "count": 0,
        }
    else:
        visualization_result = run_visualizations(
            train_features=train_features,
            output_dir=figure_dir,
            target_column=target_column,
        )

        # A visualization failure should be visible and should not be hidden
        # behind a successful report generation stage.
        if visualization_result.get("status") == "failed":
            LOGGER.error(
                "Visualization stage failed: %s",
                visualization_result.get("reason"),
            )

    # Build metadata before report generation.
    metadata = build_pipeline_metadata(
        raw_df=raw_df,
        train_df=train_df,
        validation_df=validation_df,
        test_df=test_df,
        train_features=train_features,
        validation_features=validation_features,
        test_features=test_features,
        target_column=target_column,
        raw_data_path=raw_data_path,
        random_state=random_state,
        train_size=train_size,
        validation_size=validation_size,
        test_size=test_size,
    )

    # Explicitly collect the files that are really on disk.
    verified_figures = collect_generated_figures(
        figure_dir
    )

    metadata["visualization_files_on_disk"] = {
        title: str(path)
        for title, path in verified_figures.items()
    }

    if skip_reports:
        report_result = {
            "status": "skipped",
            "reason": "Disabled by --skip-reports.",
        }
    else:
        report_result = run_report_generation(
            dataset=train_features,
            report_dir=report_dir,
            figure_dir=figure_dir,
            metadata=metadata,
            figure_mapping=(
                build_default_figure_mapping(figure_dir)
                if build_default_figure_mapping is not None
                else verified_figures
            ),
            train_shape=train_predictive.shape,
            validation_shape=validation_predictive.shape,
            test_shape=test_predictive.shape,
        )


    # ------------------------------------------------------------------
    # Step 9: Final execution summary
    # ------------------------------------------------------------------

    LOGGER.info(
        "[9/9] Writing final execution summary."
    )

    elapsed_seconds = (
        time.perf_counter()
        - pipeline_start
    )

    metadata["execution"] = {
        "status": "completed",
        "elapsed_seconds": elapsed_seconds,
        "completed_at_utc": utc_now_iso(),
    }

    metadata["artifacts"] = {
        "engineered_features": str(engineered_path),
        "train_features": str(train_path),
        "validation_features": str(validation_path),
        "test_features": str(test_path),
        "report_directory": str(report_dir),
        "figure_directory": str(figure_dir),
        "feature_quality": quality_result,
        "visualizations": visualization_result,
        "reports": report_result,
    }

    metadata["validation"] = {
        "feature_schema_consistent": True,
        "target_leakage_check": leakage_check,
        "predictive_feature_safety": {
            "train": train_safety,
            "validation": validation_safety,
            "test": test_safety,
        },
        "split_disjointness": split_check,
        "train_missing_cells": int(
            train_features.isna().sum().sum()
        ),
        "validation_missing_cells": int(
            validation_features.isna().sum().sum()
        ),
        "test_missing_cells": int(
            test_features.isna().sum().sum()
        ),
        "verified_figure_count": len(
            verified_figures
        ),
    }

    summary_path = (
        report_dir
        / "task2_execution_summary.json"
    )

    write_json(
        metadata,
        summary_path,
    )

    LOGGER.info(
        "Execution summary written to: %s",
        summary_path,
    )

    # The pipeline's core data processing completed. We deliberately keep
    # that status separate from optional visualization/report failures so
    # the exported engineered datasets remain valid artifacts.
    LOGGER.info("=" * 78)
    LOGGER.info(
        "TASK 2 PIPELINE COMPLETED"
    )
    LOGGER.info(
        "Elapsed time: %.2f seconds",
        elapsed_seconds,
    )
    LOGGER.info(
        "Verified visualization files: %d",
        len(verified_figures),
    )
    LOGGER.info("=" * 78)

    return metadata


# ---------------------------------------------------------------------------
# Command-line interface
# ---------------------------------------------------------------------------

def build_argument_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="run_task2",
        description=(
            "Run the predictive-maintenance Task 2 feature-engineering "
            "pipeline."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--raw-data",
        type=Path,
        default=DEFAULT_RAW_DATA,
        help="Path to the raw CSV dataset.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_PROCESSED_DIR,
        help="Directory where processed feature datasets are written.",
    )

    parser.add_argument(
        "--report-dir",
        type=Path,
        default=DEFAULT_REPORT_DIR,
        help=(
            "Directory where generated reports and execution metadata are "
            "written."
        ),
    )

    parser.add_argument(
        "--figure-dir",
        type=Path,
        default=DEFAULT_FIGURE_DIR,
        help=(
            "Directory where generated visualization PNG files are written. "
            "The default is reports/figures/demo."
        ),
    )

    parser.add_argument(
        "--train-size",
        type=float,
        default=DEFAULT_TRAIN_SIZE,
        help="Fraction of records assigned to the training partition.",
    )

    parser.add_argument(
        "--validation-size",
        type=float,
        default=DEFAULT_VALIDATION_SIZE,
        help=(
            "Fraction of records assigned to the validation partition."
        ),
    )

    parser.add_argument(
        "--test-size",
        type=float,
        default=DEFAULT_TEST_SIZE,
        help="Fraction of records assigned to the test partition.",
    )

    parser.add_argument(
        "--random-state",
        type=int,
        default=DEFAULT_RANDOM_STATE,
        help="Random seed used for reproducible partitioning.",
    )

    parser.add_argument(
        "--skip-visualizations",
        action="store_true",
        help="Skip visualization generation.",
    )

    parser.add_argument(
        "--skip-reports",
        action="store_true",
        help="Skip HTML/DOCX report generation.",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose DEBUG logging.",
    )

    return parser


def main(
    argv: Optional[Sequence[str]] = None,
) -> int:
    """
    Command-line entry point.

    Returns
    -------
    int
        Process exit code.
    """
    parser = build_argument_parser()
    args = parser.parse_args(argv)

    configure_logging(
        verbose=args.verbose
    )

    # Import after logging is configured so import failures are visible.
    _load_project_components()

    try:
        validate_split_sizes(
            args.train_size,
            args.validation_size,
            args.test_size,
        )

        if args.random_state < 0:
            raise ValueError(
                "--random-state must be non-negative."
            )

        metadata = run_pipeline(
            raw_data_path=args.raw_data.resolve(),
            processed_dir=args.output_dir.resolve(),
            report_dir=args.report_dir.resolve(),
            figure_dir=args.figure_dir.resolve(),
            train_size=args.train_size,
            validation_size=args.validation_size,
            test_size=args.test_size,
            random_state=args.random_state,
            skip_visualizations=args.skip_visualizations,
            skip_reports=args.skip_reports,
        )

        # Core pipeline status.
        core_status = (
            metadata.get("execution", {})
            .get("status", "unknown")
        )

        if core_status != "completed":
            LOGGER.error(
                "Core pipeline finished with status: %s",
                core_status,
            )
            return 1

        visualization_status = (
            metadata.get("artifacts", {})
            .get("visualizations", {})
            .get("status")
        )

        report_status = (
            metadata.get("artifacts", {})
            .get("reports", {})
            .get("status")
        )

        # Do not hide an actual requested visualization/report failure.
        if not args.skip_visualizations:
            if visualization_status == "failed":
                LOGGER.error(
                    "Pipeline data processing succeeded, but visualization "
                    "generation failed."
                )
                return 1

        if not args.skip_reports:
            if report_status == "failed":
                LOGGER.error(
                    "Pipeline data processing succeeded, but report "
                    "generation failed."
                )
                return 1

        return 0

    except FileNotFoundError as exc:
        LOGGER.error(
            "Input/output file error: %s",
            exc,
        )
        return 1

    except ValueError as exc:
        LOGGER.error(
            "Validation/configuration error: %s",
            exc,
        )
        return 1

    except ImportError as exc:
        LOGGER.error(
            "Missing project dependency/module: %s",
            exc,
        )
        return 1

    except KeyboardInterrupt:
        LOGGER.warning(
            "Pipeline interrupted by user."
        )
        return 1

    except Exception as exc:
        LOGGER.error(
            "Unexpected pipeline failure: %s",
            exc,
        )

        LOGGER.debug(
            "Full traceback:\n%s",
            traceback.format_exc(),
        )

        return 2


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    raise SystemExit(
        main()
    )
