"""
src/report_generator.py

Automated Task 2 Report Generation
==================================

Predictive Maintenance Project
Task 2: Feature Engineering

This module generates:

1. A professional HTML feature-engineering report.
2. A professional DOCX feature-engineering documentation report.

The reports can include:

- Dataset overview
- Feature-engineering methodology
- Time-series methodology
- Leakage-prevention methodology
- Feature inventory
- Feature-quality statistics
- Missing-value analysis
- Duplicate-feature analysis
- Correlation analysis
- Target-correlation analysis
- Distribution statistics
- Outlier diagnostics
- Feature recommendations
- Generated visualization figures
- Train/validation/test information
- Real-time feature-generation notes
- Reproducibility information

The module is intentionally independent from the actual feature
engineering implementation.

It consumes DataFrames and dictionaries generated by other modules.

Important scientific principle
------------------------------
The UCI AI4I 2020 dataset is synthetic. The report therefore explicitly
distinguishes between:

    1. AI4I/reference mode
       Physically meaningful feature engineering without pretending that
       UID is a genuine timestamp.

    2. Real time-series mode
       Genuine timestamp + machine_id based chronological processing.

This distinction prevents artificial temporal assumptions from entering
the predictive-maintenance pipeline.

Dependencies
------------
Required:
    pandas
    numpy

For DOCX generation:
    python-docx

No external web requests are performed by this module.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Sequence

import math
import json

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Optional DOCX dependency
# ---------------------------------------------------------------------

try:
    from docx import Document
    from docx.enum.section import WD_SECTION
    from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Inches, Pt

    DOCX_AVAILABLE = True

except ImportError:
    DOCX_AVAILABLE = False


# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

DEFAULT_PROJECT_NAME = (
    "Predictive Maintenance — Task 2 Feature Engineering"
)

DEFAULT_AUTHOR = "Predictive Maintenance Project"

UCI_DATASET_NAME = (
    "AI4I 2020 Predictive Maintenance Dataset"
)

UCI_DATASET_URL = (
    "https://archive.ics.uci.edu/dataset/601/"
    "ai4i%2B2020%2Bpredictive%2Bmaintenance%2Bdat"
)

UCI_DATASET_DOI = "10.24432/C5HS5C"

DEFAULT_TARGET_COLUMN = "machine_failure"


# ---------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------

@dataclass
class ReportMetadata:
    """
    Metadata displayed in generated reports.
    """

    project_name: str = DEFAULT_PROJECT_NAME

    title: str = (
        "Task 2 — Feature Engineering Report"
    )

    author: str = DEFAULT_AUTHOR

    dataset_name: str = UCI_DATASET_NAME

    dataset_source: str = (
        "UCI Machine Learning Repository"
    )

    dataset_reference: str = (
        "AI4I 2020 Predictive Maintenance Dataset"
    )

    dataset_doi: str = UCI_DATASET_DOI

    dataset_url: str = UCI_DATASET_URL

    execution_timestamp: str = field(
        default_factory=lambda: datetime.now(
            timezone.utc
        ).isoformat()
    )

    project_version: str = "1.0.0"

    time_series_mode: str = (
        "AI4I/reference mode"
    )

    timestamp_column: Optional[str] = None

    machine_id_column: Optional[str] = None

    target_column: str = DEFAULT_TARGET_COLUMN

    notes: list[str] = field(
        default_factory=list
    )


@dataclass
class ReportConfig:
    """
    Configuration controlling report generation.
    """

    output_directory: str | Path = "reports"

    figures_directory: str | Path = (
        "reports/figures"
    )

    html_filename: str = (
        "feature_engineering_report.html"
    )

    docx_filename: str = (
        "feature_engineering_documentation.docx"
    )

    max_feature_rows: int = 100

    max_correlation_pairs: int = 50

    max_target_correlations: int = 30

    max_distribution_rows: int = 50

    include_embedded_images: bool = True

    include_source_links: bool = True

    generate_docx: bool = True

    overwrite_existing: bool = True


# ---------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------

def _ensure_directory(
    directory: str | Path,
) -> Path:
    """
    Create and return a directory.
    """

    path = Path(directory)

    path.mkdir(
        parents=True,
        exist_ok=True,
    )

    return path


def _safe_value(
    value: Any,
) -> Any:
    """
    Convert numpy/pandas values into JSON/HTML-safe Python values.
    """

    if value is None:
        return None

    if isinstance(
        value,
        (np.integer,),
    ):
        return int(value)

    if isinstance(
        value,
        (np.floating,),
    ):
        if np.isnan(value):
            return None

        if np.isinf(value):
            return None

        return float(value)

    if isinstance(
        value,
        (np.bool_,),
    ):
        return bool(value)

    if pd.isna(value):
        return None

    if isinstance(
        value,
        (pd.Timestamp,),
    ):
        return value.isoformat()

    return value


def _format_value(
    value: Any,
    decimals: int = 4,
) -> str:
    """
    Format values consistently for reports.
    """

    value = _safe_value(value)

    if value is None:
        return "—"

    if isinstance(
        value,
        float,
    ):

        if abs(value) >= 100000:
            return f"{value:,.2e}"

        return f"{value:,.{decimals}f}"

    if isinstance(
        value,
        int,
    ):
        return f"{value:,}"

    return str(value)


def _escape(
    value: Any,
) -> str:
    """
    HTML-escape a value.
    """

    return escape(
        _format_value(value)
    )


def _validate_dataframe(
    df: Optional[pd.DataFrame],
    name: str,
) -> None:
    """
    Validate optional DataFrame inputs.
    """

    if df is None:
        return

    if not isinstance(
        df,
        pd.DataFrame,
    ):
        raise TypeError(
            f"{name} must be a pandas DataFrame."
        )


def _truncate_dataframe(
    df: Optional[pd.DataFrame],
    max_rows: int,
) -> pd.DataFrame:
    """
    Safely truncate a DataFrame for report presentation.
    """

    if df is None:
        return pd.DataFrame()

    if max_rows <= 0:
        return df.iloc[0:0].copy()

    return df.head(max_rows).copy()


def _relative_path(
    path: str | Path,
    base_directory: str | Path,
) -> str:
    """
    Convert a file path to a report-relative path.
    """

    path = Path(path)
    base_directory = Path(base_directory)

    try:
        return str(
            path.resolve().relative_to(
                base_directory.resolve()
            )
        ).replace(
            "\\",
            "/",
        )

    except ValueError:
        return path.name


# ---------------------------------------------------------------------
# Report data preparation
# ---------------------------------------------------------------------

def prepare_dataset_summary(
    df: pd.DataFrame,
    *,
    target_column: Optional[str] = None,
) -> pd.DataFrame:
    """
    Prepare high-level dataset statistics.
    """

    if not isinstance(
        df,
        pd.DataFrame,
    ):
        raise TypeError(
            "df must be a pandas DataFrame."
        )

    n_rows = len(df)
    n_columns = len(df.columns)

    numeric_columns = df.select_dtypes(
        include=[np.number]
    ).columns

    categorical_columns = [
        column
        for column in df.columns
        if column not in numeric_columns
    ]

    missing_cells = int(
        df.isna().sum().sum()
    )

    duplicate_rows = int(
        df.duplicated().sum()
    )

    if target_column in df.columns:

        target_missing = int(
            df[target_column].isna().sum()
        )

        target_unique = int(
            df[target_column]
            .nunique(
                dropna=True
            )
        )

    else:

        target_missing = None
        target_unique = None

    summary = pd.DataFrame(
        {
            "Metric": [
                "Rows",
                "Columns",
                "Numeric columns",
                "Categorical columns",
                "Missing cells",
                "Duplicate rows",
                "Target column",
                "Target missing values",
                "Target unique values",
            ],
            "Value": [
                n_rows,
                n_columns,
                len(numeric_columns),
                len(categorical_columns),
                missing_cells,
                duplicate_rows,
                target_column
                if target_column
                else "Not supplied",
                target_missing,
                target_unique,
            ],
        }
    )

    return summary


def prepare_feature_inventory(
    df: pd.DataFrame,
    *,
    target_column: Optional[str] = None,
    exclude_columns: Optional[
        Iterable[str]
    ] = None,
) -> pd.DataFrame:
    """
    Build a feature inventory for reporting.
    """

    exclude = set(
        exclude_columns or []
    )

    if target_column:
        exclude.add(
            target_column
        )

    rows = []

    for column in df.columns:

        if column in exclude:
            continue

        series = df[column]

        numeric = pd.api.types.is_numeric_dtype(
            series
        )

        rows.append(
            {
                "Feature": column,
                "Data type": str(
                    series.dtype
                ),
                "Numeric": (
                    "Yes"
                    if numeric
                    else "No"
                ),
                "Missing": int(
                    series.isna().sum()
                ),
                "Missing %": (
                    float(
                        series.isna().mean()
                        * 100
                    )
                ),
                "Unique values": int(
                    series.nunique(
                        dropna=True
                    )
                ),
            }
        )

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------
# HTML rendering helpers
# ---------------------------------------------------------------------

def dataframe_to_html(
    df: Optional[pd.DataFrame],
    *,
    max_rows: int = 100,
    decimals: int = 4,
    empty_message: str = (
        "No information available."
    ),
) -> str:
    """
    Convert a DataFrame into a professional HTML table.
    """

    if df is None or df.empty:

        return (
            '<div class="empty-message">'
            f"{escape(empty_message)}"
            "</div>"
        )

    working = _truncate_dataframe(
        df,
        max_rows,
    )

    html = [
        '<div class="table-container">',
        '<table class="data-table">',
        "<thead>",
        "<tr>",
    ]

    for column in working.columns:

        html.append(
            "<th>"
            + escape(
                str(column)
            )
            + "</th>"
        )

    html.extend(
        [
            "</tr>",
            "</thead>",
            "<tbody>",
        ]
    )

    for _, row in working.iterrows():

        html.append("<tr>")

        for value in row:

            html.append(
                "<td>"
                + escape(
                    _format_value(
                        value,
                        decimals=decimals,
                    )
                )
                + "</td>"
            )

        html.append("</tr>")

    html.extend(
        [
            "</tbody>",
            "</table>",
            "</div>",
        ]
    )

    if len(df) > max_rows:

        html.append(
            '<p class="table-note">'
            f"Showing first {max_rows:,} of "
            f"{len(df):,} rows."
            "</p>"
        )

    return "\n".join(html)


def metric_card(
    label: str,
    value: Any,
    description: Optional[str] = None,
) -> str:
    """
    Generate an HTML metric card.
    """

    description_html = ""

    if description:

        description_html = (
            '<div class="metric-description">'
            + escape(description)
            + "</div>"
        )

    return (
        '<div class="metric-card">'
        '<div class="metric-label">'
        + escape(label)
        + "</div>"
        '<div class="metric-value">'
        + escape(_format_value(value))
        + "</div>"
        + description_html
        + "</div>"
    )


def section(
    section_id: str,
    title: str,
    content: str,
) -> str:
    """
    Generate a report section.
    """

    return (
        f'<section id="{escape(section_id)}" '
        'class="report-section">'
        f"<h2>{escape(title)}</h2>"
        f"{content}"
        "</section>"
    )


# ---------------------------------------------------------------------
# HTML CSS
# ---------------------------------------------------------------------

def get_html_css() -> str:
    """
    Return the complete report CSS.
    """

    return r"""
<style>
:root {
    --navy: #17365D;
    --blue: #2E75B6;
    --blue-light: #D9EAF7;
    --green: #548235;
    --orange: #C55A11;
    --red: #A61C00;
    --text: #263238;
    --muted: #667085;
    --background: #F6F8FB;
    --card: #FFFFFF;
    --border: #D9E2EC;
    --shadow: 0 4px 18px rgba(31, 41, 55, 0.07);
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
    padding: 0;
    background: var(--background);
    color: var(--text);
    font-family:
        -apple-system,
        BlinkMacSystemFont,
        "Segoe UI",
        Roboto,
        Arial,
        sans-serif;
    line-height: 1.6;
}

.report-container {
    width: min(1440px, 94%);
    margin: 0 auto;
}

.report-header {
    margin: 28px 0;
    padding: 42px 48px;
    background:
        linear-gradient(
            135deg,
            #17365D 0%,
            #2E75B6 100%
        );
    color: white;
    border-radius: 18px;
    box-shadow: var(--shadow);
}

.report-header h1 {
    margin: 0 0 12px 0;
    font-size: 34px;
    line-height: 1.2;
}

.report-header .subtitle {
    font-size: 17px;
    opacity: 0.92;
}

.metadata-grid {
    display: grid;
    grid-template-columns:
        repeat(auto-fit, minmax(220px, 1fr));
    gap: 14px;
    margin-top: 28px;
}

.metadata-item {
    padding: 13px 15px;
    border-radius: 10px;
    background: rgba(255, 255, 255, 0.12);
}

.metadata-label {
    display: block;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    opacity: 0.75;
    margin-bottom: 4px;
}

.metadata-value {
    font-size: 14px;
    font-weight: 600;
}

.report-section {
    margin: 28px 0;
    padding: 30px;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 16px;
    box-shadow: var(--shadow);
}

.report-section h2 {
    margin-top: 0;
    padding-bottom: 12px;
    border-bottom: 2px solid var(--blue-light);
    color: var(--navy);
    font-size: 23px;
}

.report-section h3 {
    color: var(--navy);
    margin-top: 28px;
}

.metrics-grid {
    display: grid;
    grid-template-columns:
        repeat(auto-fit, minmax(190px, 1fr));
    gap: 16px;
}

.metric-card {
    padding: 20px;
    border: 1px solid var(--border);
    border-radius: 12px;
    background: #FFFFFF;
}

.metric-label {
    color: var(--muted);
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
}

.metric-value {
    margin-top: 5px;
    color: var(--navy);
    font-size: 28px;
    font-weight: 750;
}

.metric-description {
    margin-top: 5px;
    color: var(--muted);
    font-size: 12px;
}

.table-container {
    overflow-x: auto;
    margin-top: 14px;
}

.data-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
}

.data-table th {
    padding: 11px 10px;
    background: var(--navy);
    color: white;
    text-align: left;
    white-space: nowrap;
}

.data-table td {
    padding: 9px 10px;
    border-bottom: 1px solid var(--border);
    vertical-align: top;
}

.data-table tr:nth-child(even) {
    background: #F8FAFC;
}

.data-table tr:hover {
    background: var(--blue-light);
}

.table-note {
    color: var(--muted);
    font-size: 12px;
    font-style: italic;
}

.figure-grid {
    display: grid;
    grid-template-columns:
        repeat(auto-fit, minmax(440px, 1fr));
    gap: 20px;
    margin-top: 18px;
}

.figure-card {
    padding: 14px;
    background: white;
    border: 1px solid var(--border);
    border-radius: 12px;
}

.figure-card img {
    width: 100%;
    height: auto;
    display: block;
    border-radius: 8px;
}

.figure-caption {
    margin-top: 9px;
    color: var(--muted);
    font-size: 12px;
}

.callout {
    margin: 18px 0;
    padding: 18px 20px;
    border-left: 5px solid var(--blue);
    background: #F2F7FC;
    border-radius: 8px;
}

.callout.warning {
    border-left-color: var(--orange);
    background: #FFF6ED;
}

.callout.danger {
    border-left-color: var(--red);
    background: #FFF1F0;
}

.callout.success {
    border-left-color: var(--green);
    background: #F2F8EE;
}

.badge {
    display: inline-block;
    padding: 4px 9px;
    margin-right: 5px;
    border-radius: 999px;
    background: var(--blue-light);
    color: var(--navy);
    font-size: 11px;
    font-weight: 700;
}

.feature-list {
    display: grid;
    grid-template-columns:
        repeat(auto-fit, minmax(260px, 1fr));
    gap: 10px;
    margin: 15px 0;
    padding: 0;
    list-style: none;
}

.feature-list li {
    padding: 11px 14px;
    background: #F8FAFC;
    border: 1px solid var(--border);
    border-radius: 8px;
}

pre.code-block {
    overflow-x: auto;
    padding: 18px;
    background: #17202A;
    color: #ECF0F1;
    border-radius: 10px;
    font-size: 12px;
}

.report-footer {
    margin: 30px 0 50px 0;
    padding: 22px;
    color: var(--muted);
    font-size: 12px;
    text-align: center;
}

.empty-message {
    padding: 18px;
    background: #F8FAFC;
    color: var(--muted);
    border-radius: 8px;
    font-style: italic;
}

a {
    color: var(--blue);
}

@media print {
    body {
        background: white;
    }

    .report-section {
        box-shadow: none;
        break-inside: avoid;
    }

    .report-header {
        box-shadow: none;
    }
}
</style>
"""


# ---------------------------------------------------------------------
# HTML report generation
# ---------------------------------------------------------------------

def generate_html_report(
    *,
    metadata: ReportMetadata,
    config: ReportConfig,
    dataset: pd.DataFrame,
    quality_results: Optional[
        Mapping[str, pd.DataFrame]
    ] = None,
    engineered_features: Optional[
        Sequence[str]
    ] = None,
    feature_descriptions: Optional[
        Mapping[str, str]
    ] = None,
    figures: Optional[
        Mapping[str, str | Path]
    ] = None,
    train_shape: Optional[tuple[int, int]] = None,
    validation_shape: Optional[
        tuple[int, int]
    ] = None,
    test_shape: Optional[
        tuple[int, int]
    ] = None,
    methodology_notes: Optional[
        Sequence[str]
    ] = None,
    leakage_notes: Optional[
        Sequence[str]
    ] = None,
    realtime_notes: Optional[
        Sequence[str]
    ] = None,
) -> Path:
    """
    Generate the complete HTML report.

    Parameters
    ----------
    metadata:
        Report metadata.

    config:
        Report configuration.

    dataset:
        Engineered dataset being documented.

    quality_results:
        Dictionary returned by feature-quality audit functions.

    engineered_features:
        Names of generated features.

    feature_descriptions:
        Optional mapping from feature names to descriptions.

    figures:
        Mapping of figure title/name to image path.

    train_shape, validation_shape, test_shape:
        Optional split dimensions.

    methodology_notes:
        Feature-engineering methodology notes.

    leakage_notes:
        Leakage-prevention notes.

    realtime_notes:
        Real-time/online processing notes.

    Returns
    -------
    pathlib.Path
        Generated HTML path.
    """

    _validate_dataframe(
        dataset,
        "dataset",
    )

    output_directory = _ensure_directory(
        config.output_directory
    )

    figures_directory = _ensure_directory(
        config.figures_directory
    )

    quality_results = (
        quality_results
        or {}
    )

    engineered_features = list(
        engineered_features
        or []
    )

    feature_descriptions = (
        feature_descriptions
        or {}
    )

    figures = figures or {}

    methodology_notes = list(
        methodology_notes
        or []
    )

    leakage_notes = list(
        leakage_notes
        or []
    )

    realtime_notes = list(
        realtime_notes
        or []
    )

    # --------------------------------------------------------------
    # Dataset summary
    # --------------------------------------------------------------

    dataset_summary = prepare_dataset_summary(
        dataset,
        target_column=metadata.target_column,
    )

    numeric_features = len(
        dataset.select_dtypes(
            include=[np.number]
        ).columns
    )

    total_missing = int(
        dataset.isna().sum().sum()
    )

    duplicate_rows = int(
        dataset.duplicated().sum()
    )

    # --------------------------------------------------------------
    # Quality outputs
    # --------------------------------------------------------------

    feature_statistics = quality_results.get(
        "feature_statistics",
        pd.DataFrame(),
    )

    missing_features = quality_results.get(
        "missing_features",
        pd.DataFrame(),
    )

    duplicate_pairs = quality_results.get(
        "duplicate_feature_pairs",
        pd.DataFrame(),
    )

    infinite_values = quality_results.get(
        "infinite_values",
        pd.DataFrame(),
    )

    correlation_matrix = quality_results.get(
        "correlation_matrix",
        pd.DataFrame(),
    )

    highly_correlated = quality_results.get(
        "highly_correlated_features",
        pd.DataFrame(),
    )

    target_correlations = quality_results.get(
        "target_correlations",
        pd.DataFrame(),
    )

    distribution_summary = quality_results.get(
        "distribution_summary",
        pd.DataFrame(),
    )

    outlier_summary = quality_results.get(
        "outlier_summary",
        pd.DataFrame(),
    )

    leakage_report = quality_results.get(
        "leakage_report",
        pd.DataFrame(),
    )

    recommendations = quality_results.get(
        "recommendations",
        pd.DataFrame(),
    )

    # --------------------------------------------------------------
    # Feature inventory
    # --------------------------------------------------------------

    inventory = prepare_feature_inventory(
        dataset,
        target_column=metadata.target_column,
    )

    # --------------------------------------------------------------
    # Header
    # --------------------------------------------------------------

    header = f"""
<header class="report-header">

    <h1>{escape(metadata.title)}</h1>

    <div class="subtitle">
        {escape(metadata.project_name)}
    </div>

    <div class="metadata-grid">

        <div class="metadata-item">
            <span class="metadata-label">
                Dataset
            </span>
            <span class="metadata-value">
                {escape(metadata.dataset_name)}
            </span>
        </div>

        <div class="metadata-item">
            <span class="metadata-label">
                Dataset Source
            </span>
            <span class="metadata-value">
                {escape(metadata.dataset_source)}
            </span>
        </div>

        <div class="metadata-item">
            <span class="metadata-label">
                Processing Mode
            </span>
            <span class="metadata-value">
                {escape(metadata.time_series_mode)}
            </span>
        </div>

        <div class="metadata-item">
            <span class="metadata-label">
                Target
            </span>
            <span class="metadata-value">
                {escape(metadata.target_column)}
            </span>
        </div>

        <div class="metadata-item">
            <span class="metadata-label">
                Generated
            </span>
            <span class="metadata-value">
                {escape(metadata.execution_timestamp)}
            </span>
        </div>

        <div class="metadata-item">
            <span class="metadata-label">
                Project Version
            </span>
            <span class="metadata-value">
                {escape(metadata.project_version)}
            </span>
        </div>

    </div>

</header>
"""

    # --------------------------------------------------------------
    # Executive summary
    # --------------------------------------------------------------

    executive_content = f"""
<div class="metrics-grid">

    {metric_card(
        "Observations",
        len(dataset),
        "Rows in the engineered dataset"
    )}

    {metric_card(
        "Columns",
        len(dataset.columns),
        "Total columns after engineering"
    )}

    {metric_card(
        "Numeric Features",
        numeric_features,
        "Numeric columns available for analysis"
    )}

    {metric_card(
        "Missing Cells",
        total_missing,
        "Missing cells after feature engineering"
    )}

    {metric_card(
        "Duplicate Rows",
        duplicate_rows,
        "Exact duplicate observations"
    )}

    {metric_card(
        "Engineered Features",
        len(engineered_features),
        "Features created by Task 2"
    )}

</div>

<div class="callout">

<strong>Project objective.</strong>

Task 2 transforms raw predictive-maintenance sensor measurements into
physically meaningful, statistically informative and leakage-safe
features suitable for downstream machine-learning and real-time
prediction.

</div>

<div class="callout warning">

<strong>Dataset interpretation.</strong>

The AI4I 2020 dataset is synthetic. Its UID column is treated as an
identifier rather than being automatically interpreted as a genuine
machine timestamp. Genuine chronological rolling and lag features
require a real timestamp and, ideally, a machine identifier.

</div>
"""

    executive_section = section(
        "executive-summary",
        "Executive Summary",
        executive_content,
    )

    # --------------------------------------------------------------
    # Dataset section
    # --------------------------------------------------------------

    source_link = ""

    if config.include_source_links:

        source_link = f"""
<p>
    <strong>Official dataset source:</strong>
    <a href="{escape(metadata.dataset_url)}"
       target="_blank"
       rel="noopener">
        UCI Machine Learning Repository
    </a>
</p>

<p>
    <strong>Dataset DOI:</strong>
    {escape(metadata.dataset_doi)}
</p>
"""

    dataset_content = (
        source_link
        + dataframe_to_html(
            dataset_summary,
            max_rows=20,
        )
    )

    dataset_section = section(
        "dataset",
        "Dataset Overview",
        dataset_content,
    )

    # --------------------------------------------------------------
    # Methodology section
    # --------------------------------------------------------------

    default_methodology = [
        "Raw sensor measurements are retained as the source variables.",
        "Physically meaningful transformations are generated from temperature, speed, torque and tool-wear measurements.",
        "Temporal lag and rolling features are generated only when genuine chronological ordering is available.",
        "Machine-specific online statistics are maintained separately for real-time processing.",
        "Missing values are handled without using future observations.",
        "Feature calculations are fitted or learned on training data where required.",
        "Train, validation and test transformations use the same feature definitions.",
        "Feature-quality checks are executed before downstream modeling.",
    ]

    methodology_items = (
        methodology_notes
        if methodology_notes
        else default_methodology
    )

    methodology_html = (
        "<ul>"
        + "".join(
            "<li>"
            + escape(str(note))
            + "</li>"
            for note in methodology_items
        )
        + "</ul>"
    )

    methodology_html += """
<h3>Feature Families</h3>

<ul class="feature-list">

<li>Time-based features</li>
<li>Lag features</li>
<li>Rolling mean</li>
<li>Rolling standard deviation</li>
<li>Rolling minimum / maximum</li>
<li>Rolling median</li>
<li>Exponentially weighted moving averages</li>
<li>Sensor differences</li>
<li>Sensor ratios</li>
<li>Temperature gap</li>
<li>Mechanical power</li>
<li>Torque × rotational-speed interaction</li>
<li>Tool-wear transformations</li>
<li>Rate-of-change features</li>
<li>Z-score / anomaly features</li>
<li>Interaction features</li>
<li>Operating-condition features</li>
<li>Missing-value handling</li>
<li>Constant/duplicate feature removal</li>

</ul>
"""

    methodology_section = section(
        "methodology",
        "Feature Engineering Methodology",
        methodology_html,
    )

    # --------------------------------------------------------------
    # Leakage section
    # --------------------------------------------------------------

    default_leakage_notes = [
        "UID is not treated as a genuine timestamp for AI4I.",
        "Failure-mode label columns are not used as predictive sensor features.",
        "Rolling and lag features use current and historical observations only.",
        "No future observation is used to construct a past feature.",
        "Data-driven imputers/scalers/encoders must be fitted on training data only.",
        "Feature selection decisions are based on training data rather than the full dataset.",
        "Validation and test data are transformed using parameters learned from training data.",
    ]

    leakage_items = (
        leakage_notes
        if leakage_notes
        else default_leakage_notes
    )

    leakage_html = (
        '<div class="callout danger">'
        "<strong>Leakage prevention.</strong>"
        "<ul>"
        + "".join(
            "<li>"
            + escape(str(note))
            + "</li>"
            for note in leakage_items
        )
        + "</ul>"
        "</div>"
    )

    if (
        not leakage_report.empty
        and "potential_leakage" in leakage_report.columns
    ):

        potential_count = int(
            leakage_report[
                "potential_leakage"
            ].sum()
        )

        leakage_html += metric_card(
            "Potential Leakage Flags",
            potential_count,
            "Requires manual review",
        )

        leakage_html += dataframe_to_html(
            leakage_report,
            max_rows=config.max_feature_rows,
        )

    leakage_section = section(
        "leakage",
        "Leakage and Temporal-Safety Assessment",
        leakage_html,
    )

    # --------------------------------------------------------------
    # Feature inventory
    # --------------------------------------------------------------

    inventory_content = dataframe_to_html(
        inventory,
        max_rows=config.max_feature_rows,
    )

    if engineered_features:

        feature_list = (
            "<h3>Generated Feature Names</h3>"
            "<ul class='feature-list'>"
            + "".join(
                "<li>"
                + escape(feature)
                + (
                    "<br><small>"
                    + escape(
                        feature_descriptions.get(
                            feature,
                            "",
                        )
                    )
                    + "</small>"
                    if feature in feature_descriptions
                    else ""
                )
                + "</li>"
                for feature in engineered_features
            )
            + "</ul>"
        )

        inventory_content = (
            feature_list
            + inventory_content
        )

    inventory_section = section(
        "feature-inventory",
        "Feature Inventory",
        inventory_content,
    )

    # --------------------------------------------------------------
    # Quality section
    # --------------------------------------------------------------

    quality_content = ""

    if not feature_statistics.empty:

        quality_content += (
            "<h3>Feature Statistics</h3>"
            + dataframe_to_html(
                feature_statistics,
                max_rows=config.max_feature_rows,
            )
        )

    if not missing_features.empty:

        quality_content += (
            "<h3>Features with Substantial Missingness</h3>"
            + dataframe_to_html(
                missing_features,
                max_rows=config.max_feature_rows,
            )
        )

    if not duplicate_pairs.empty:

        quality_content += (
            "<h3>Duplicate Feature Pairs</h3>"
            + dataframe_to_html(
                duplicate_pairs,
                max_rows=config.max_feature_rows,
            )
        )

    if not infinite_values.empty:

        quality_content += (
            "<h3>Infinite-Value Diagnostics</h3>"
            + dataframe_to_html(
                infinite_values,
                max_rows=config.max_feature_rows,
            )
        )

    if not recommendations.empty:

        quality_content += (
            "<h3>Feature Recommendations</h3>"
            + dataframe_to_html(
                recommendations,
                max_rows=config.max_feature_rows,
            )
        )

    if not quality_content:

        quality_content = (
            '<div class="empty-message">'
            "No feature-quality results were supplied."
            "</div>"
        )

    quality_section = section(
        "quality",
        "Feature Quality Assessment",
        quality_content,
    )

    # --------------------------------------------------------------
    # Correlation section
    # --------------------------------------------------------------

    correlation_content = ""

    if not highly_correlated.empty:

        correlation_content += (
            "<h3>Highly Correlated Feature Pairs</h3>"
            + dataframe_to_html(
                highly_correlated,
                max_rows=config.max_correlation_pairs,
            )
        )

    if not target_correlations.empty:

        correlation_content += (
            "<h3>Feature–Target Correlations</h3>"
            + dataframe_to_html(
                target_correlations,
                max_rows=config.max_target_correlations,
            )
        )

    if correlation_content == "":

        correlation_content = (
            '<div class="empty-message">'
            "No correlation diagnostics were supplied."
            "</div>"
        )

    correlation_section = section(
        "correlations",
        "Correlation Analysis",
        correlation_content,
    )

    # --------------------------------------------------------------
    # Distribution section
    # --------------------------------------------------------------

    distribution_content = ""

    if not distribution_summary.empty:

        distribution_content = dataframe_to_html(
            distribution_summary,
            max_rows=config.max_distribution_rows,
        )

    if not outlier_summary.empty:

        distribution_content += (
            "<h3>IQR Outlier Diagnostics</h3>"
            + dataframe_to_html(
                outlier_summary,
                max_rows=config.max_distribution_rows,
            )
        )

    if not distribution_content:

        distribution_content = (
            '<div class="empty-message">'
            "No distribution diagnostics were supplied."
            "</div>"
        )

    distribution_section = section(
        "distribution",
        "Distribution and Outlier Diagnostics",
        distribution_content,
    )

    # --------------------------------------------------------------
    # Split section
    # --------------------------------------------------------------

    split_rows = []

    for name, shape in [
        ("Training", train_shape),
        ("Validation", validation_shape),
        ("Test", test_shape),
    ]:

        if shape is None:
            continue

        split_rows.append(
            {
                "Split": name,
                "Rows": shape[0],
                "Columns": shape[1],
            }
        )

    split_df = pd.DataFrame(
        split_rows
    )

    split_content = ""

    if not split_df.empty:

        split_content = dataframe_to_html(
            split_df,
            max_rows=10,
        )

    else:

        split_content = (
            '<div class="empty-message">'
            "Train/validation/test shapes were not supplied."
            "</div>"
        )

    split_content += """
<div class="callout success">

<strong>Recommended split policy.</strong>

For genuine machine time-series data, chronological splitting or
machine-aware grouped splitting should be used. Random row-wise
splitting can allow highly related observations from the same machine
and time period to appear across both training and evaluation sets.

</div>
"""

    split_section = section(
        "splits",
        "Train / Validation / Test Compatibility",
        split_content,
    )

    # --------------------------------------------------------------
    # Real-time section
    # --------------------------------------------------------------

    realtime_content = f"""
<div class="metrics-grid">

{metric_card(
    "Processing Mode",
    metadata.time_series_mode,
)}

{metric_card(
    "Timestamp Column",
    metadata.timestamp_column or "Not supplied",
)}

{metric_card(
    "Machine ID Column",
    metadata.machine_id_column or "Not supplied",
)}

</div>
"""

    if realtime_notes:

        realtime_content += (
            "<ul>"
            + "".join(
                "<li>"
                + escape(str(note))
                + "</li>"
                for note in realtime_notes
            )
            + "</ul>"
        )

    else:

        realtime_content += """
<ul>
<li>Online features should use only information available up to the current event.</li>
<li>Stateful rolling statistics should be maintained per machine.</li>
<li>Production feature definitions must exactly match offline feature definitions.</li>
<li>Missing sensor readings should not cause future information to be backfilled into the past.</li>
<li>Production feature pipelines should monitor feature drift and data-quality violations.</li>
</ul>
"""

    realtime_section = section(
        "realtime",
        "Real-Time / Online Feature Engineering",
        realtime_content,
    )

    # --------------------------------------------------------------
    # Visualization section
    # --------------------------------------------------------------

    figures_content = ""

    if figures:

        figures_content += (
            '<div class="figure-grid">'
        )

        for figure_name, figure_path in figures.items():

            figure_path = Path(
                figure_path
            )

            if not figure_path.exists():
                continue

            relative_path = _relative_path(
                figure_path,
                output_directory,
            )

            figures_content += f"""
<div class="figure-card">

<img
    src="{escape(relative_path)}"
    alt="{escape(str(figure_name))}"
>

<div class="figure-caption">
    {escape(str(figure_name))}
</div>

</div>
"""

        figures_content += "</div>"

    if not figures_content:

        figures_content = (
            '<div class="empty-message">'
            "No figures were supplied."
            "</div>"
        )

    visualization_section = section(
        "visualizations",
        "Visual Diagnostics",
        figures_content,
    )

    # --------------------------------------------------------------
    # Conclusion
    # --------------------------------------------------------------

    conclusion_content = """
<div class="callout success">

<strong>Task 2 completion criteria.</strong>

The feature-engineering pipeline should be considered ready for
downstream modeling only after:

<ul>
<li>All feature definitions are reproducible.</li>
<li>Temporal features are leakage-safe.</li>
<li>Training-only fitting is used for learned transformations.</li>
<li>Constant and duplicate features have been reviewed.</li>
<li>Missing and infinite values have been addressed.</li>
<li>Highly correlated features have been reviewed.</li>
<li>Potential leakage has been investigated.</li>
<li>Train/validation/test transformations are compatible.</li>
<li>Offline and online feature definitions are consistent.</li>
<li>Feature quality has been documented.</li>
</ul>

</div>
"""

    conclusion_section = section(
        "conclusion",
        "Task 2 Conclusions and Readiness",
        conclusion_content,
    )

    # --------------------------------------------------------------
    # Footer
    # --------------------------------------------------------------

    footer = f"""
<footer class="report-footer">

<p>
    Generated automatically by the Predictive Maintenance Task 2
    reporting pipeline.
</p>

<p>
    Dataset reference:
    {escape(metadata.dataset_reference)}
    · DOI:
    {escape(metadata.dataset_doi)}
</p>

<p>
    Report generated:
    {escape(metadata.execution_timestamp)}
</p>

</footer>
"""

    # --------------------------------------------------------------
    # Complete HTML
    # --------------------------------------------------------------

    html = f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">

<meta
    name="viewport"
    content="width=device-width, initial-scale=1"
>

<title>
    {escape(metadata.title)}
</title>

{get_html_css()}

</head>

<body>

<div class="report-container">

{header}

{executive_section}

{dataset_section}

{methodology_section}

{leakage_section}

{inventory_section}

{quality_section}

{correlation_section}

{distribution_section}

{split_section}

{realtime_section}

{visualization_section}

{conclusion_section}

{footer}

</div>

</body>

</html>
"""

    output_path = (
        output_directory
        / config.html_filename
    )

    if (
        output_path.exists()
        and not config.overwrite_existing
    ):

        raise FileExistsError(
            f"Report already exists: {output_path}"
        )

    output_path.write_text(
        html,
        encoding="utf-8",
    )

    return output_path


# ---------------------------------------------------------------------
# DOCX helpers
# ---------------------------------------------------------------------

def _set_cell_shading(
    cell,
    fill: str,
) -> None:
    """
    Apply background shading to a DOCX table cell.
    """

    if not DOCX_AVAILABLE:
        return

    tc_pr = cell._tc.get_or_add_tcPr()

    shd = OxmlElement(
        "w:shd"
    )

    shd.set(
        qn("w:fill"),
        fill,
    )

    tc_pr.append(shd)


def _set_cell_text_color(
    cell,
    color: str,
) -> None:
    """
    Apply text color to all paragraphs in a DOCX cell.
    """

    if not DOCX_AVAILABLE:
        return

    for paragraph in cell.paragraphs:

        for run in paragraph.runs:

            run.font.color.rgb = (
                __import__(
                    "docx"
                ).shared.RGBColor.from_string(
                    color
                )
            )


def _set_cell_bold(
    cell,
    bold: bool = True,
) -> None:
    """
    Set all cell text to bold/normal.
    """

    if not DOCX_AVAILABLE:
        return

    for paragraph in cell.paragraphs:

        for run in paragraph.runs:

            run.bold = bold


def add_docx_table(
    document,
    df: Optional[pd.DataFrame],
    *,
    max_rows: int = 100,
    font_size: int = 8,
) -> None:
    """
    Add a DataFrame as a formatted DOCX table.
    """

    if not DOCX_AVAILABLE:
        raise RuntimeError(
            "python-docx is required to generate DOCX reports."
        )

    if df is None or df.empty:

        paragraph = document.add_paragraph(
            "No information available."
        )

        paragraph.runs[0].italic = True

        return

    working = _truncate_dataframe(
        df,
        max_rows,
    )

    table = document.add_table(
        rows=1,
        cols=len(working.columns),
    )

    table.style = "Table Grid"

    header_cells = table.rows[0].cells

    for index, column in enumerate(
        working.columns
    ):

        cell = header_cells[index]

        cell.text = str(column)

        _set_cell_shading(
            cell,
            "17365D",
        )

        _set_cell_bold(
            cell,
            True,
        )

        _set_cell_text_color(
            cell,
            "FFFFFF",
        )

        cell.vertical_alignment = (
            WD_CELL_VERTICAL_ALIGNMENT.CENTER
        )

        for paragraph in cell.paragraphs:

            for run in paragraph.runs:

                run.font.size = Pt(
                    font_size
                )

    for _, row in working.iterrows():

        cells = table.add_row().cells

        for index, value in enumerate(row):

            cells[index].text = (
                _format_value(
                    value
                )
            )

            cells[index].vertical_alignment = (
                WD_CELL_VERTICAL_ALIGNMENT.CENTER
            )

            for paragraph in cells[index].paragraphs:

                for run in paragraph.runs:

                    run.font.size = Pt(
                        font_size
                    )

    if len(df) > max_rows:

        paragraph = document.add_paragraph(
            f"Showing first {max_rows:,} "
            f"of {len(df):,} rows."
        )

        paragraph.runs[0].italic = True


def add_docx_heading(
    document,
    text: str,
    level: int = 1,
) -> None:
    """
    Add a formatted DOCX heading.
    """

    heading = document.add_heading(
        text,
        level=level,
    )

    for run in heading.runs:

        run.font.name = "Aptos"

        if level == 1:
            run.font.size = Pt(20)
        elif level == 2:
            run.font.size = Pt(15)
        else:
            run.font.size = Pt(12)


def add_docx_bullet_list(
    document,
    items: Sequence[str],
) -> None:
    """
    Add bullet points to a DOCX document.
    """

    for item in items:

        paragraph = document.add_paragraph(
            style="List Bullet"
        )

        paragraph.add_run(
            str(item)
        )


def add_docx_callout(
    document,
    title: str,
    text: str,
) -> None:
    """
    Add a visually distinct DOCX callout.
    """

    table = document.add_table(
        rows=1,
        cols=1,
    )

    table.style = "Table Grid"

    cell = table.cell(
        0,
        0,
    )

    _set_cell_shading(
        cell,
        "F2F7FC",
    )

    paragraph = cell.paragraphs[0]

    run = paragraph.add_run(
        title + "\n"
    )

    run.bold = True
    run.font.size = Pt(11)

    run = paragraph.add_run(
        text
    )

    run.font.size = Pt(10)


def add_docx_figure(
    document,
    figure_path: str | Path,
    caption: str,
    *,
    width_inches: float = 6.5,
) -> None:
    """
    Add a figure and caption to a DOCX report.
    """

    figure_path = Path(
        figure_path
    )

    if not figure_path.exists():
        return

    paragraph = document.add_paragraph()

    paragraph.alignment = (
        WD_ALIGN_PARAGRAPH.CENTER
    )

    run = paragraph.add_run()

    run.add_picture(
        str(figure_path),
        width=Inches(
            width_inches
        ),
    )

    caption_paragraph = (
        document.add_paragraph()
    )

    caption_paragraph.alignment = (
        WD_ALIGN_PARAGRAPH.CENTER
    )

    caption_run = (
        caption_paragraph.add_run(
            caption
        )
    )

    caption_run.italic = True
    caption_run.font.size = Pt(9)


# ---------------------------------------------------------------------
# DOCX report generation
# ---------------------------------------------------------------------

def generate_docx_report(
    *,
    metadata: ReportMetadata,
    config: ReportConfig,
    dataset: pd.DataFrame,
    quality_results: Optional[
        Mapping[str, pd.DataFrame]
    ] = None,
    engineered_features: Optional[
        Sequence[str]
    ] = None,
    feature_descriptions: Optional[
        Mapping[str, str]
    ] = None,
    figures: Optional[
        Mapping[str, str | Path]
    ] = None,
    train_shape: Optional[
        tuple[int, int]
    ] = None,
    validation_shape: Optional[
        tuple[int, int]
    ] = None,
    test_shape: Optional[
        tuple[int, int]
    ] = None,
    methodology_notes: Optional[
        Sequence[str]
    ] = None,
    leakage_notes: Optional[
        Sequence[str]
    ] = None,
    realtime_notes: Optional[
        Sequence[str]
    ] = None,
) -> Path:
    """
    Generate a professional DOCX documentation report.
    """

    if not DOCX_AVAILABLE:

        raise ImportError(
            "DOCX generation requires python-docx. "
            "Install it with: pip install python-docx"
        )

    _validate_dataframe(
        dataset,
        "dataset",
    )

    output_directory = _ensure_directory(
        config.output_directory
    )

    quality_results = (
        quality_results
        or {}
    )

    engineered_features = list(
        engineered_features
        or []
    )

    feature_descriptions = (
        feature_descriptions
        or {}
    )

    figures = figures or {}

    methodology_notes = list(
        methodology_notes
        or []
    )

    leakage_notes = list(
        leakage_notes
        or []
    )

    realtime_notes = list(
        realtime_notes
        or []
    )

    # --------------------------------------------------------------
    # Create document
    # --------------------------------------------------------------

    document = Document()

    section_object = document.sections[0]

    section_object.top_margin = Inches(
        0.65
    )

    section_object.bottom_margin = Inches(
        0.65
    )

    section_object.left_margin = Inches(
        0.75
    )

    section_object.right_margin = Inches(
        0.75
    )

    # --------------------------------------------------------------
    # Default font
    # --------------------------------------------------------------

    styles = document.styles

    styles["Normal"].font.name = (
        "Aptos"
    )

    styles["Normal"].font.size = Pt(
        10
    )

    # --------------------------------------------------------------
    # Title page
    # --------------------------------------------------------------

    title = document.add_paragraph()

    title.alignment = (
        WD_ALIGN_PARAGRAPH.CENTER
    )

    run = title.add_run(
        metadata.title
    )

    run.bold = True
    run.font.size = Pt(26)

    run.font.name = "Aptos Display"

    subtitle = document.add_paragraph()

    subtitle.alignment = (
        WD_ALIGN_PARAGRAPH.CENTER
    )

    run = subtitle.add_run(
        metadata.project_name
    )

    run.font.size = Pt(15)

    run.font.color.rgb = (
        __import__(
            "docx"
        ).shared.RGBColor(
            46,
            117,
            182,
        )
    )

    metadata_table = document.add_table(
        rows=6,
        cols=2,
    )

    metadata_table.style = (
        "Table Grid"
    )

    metadata_rows = [
        (
            "Dataset",
            metadata.dataset_name,
        ),
        (
            "Source",
            metadata.dataset_source,
        ),
        (
            "Dataset DOI",
            metadata.dataset_doi,
        ),
        (
            "Processing mode",
            metadata.time_series_mode,
        ),
        (
            "Target",
            metadata.target_column,
        ),
        (
            "Generated",
            metadata.execution_timestamp,
        ),
    ]

    for row_index, (
        label,
        value,
    ) in enumerate(
        metadata_rows
    ):

        metadata_table.cell(
            row_index,
            0,
        ).text = label

        metadata_table.cell(
            row_index,
            1,
        ).text = str(value)

        _set_cell_shading(
            metadata_table.cell(
                row_index,
                0,
            ),
            "17365D",
        )

        _set_cell_text_color(
            metadata_table.cell(
                row_index,
                0,
            ),
            "FFFFFF",
        )

        _set_cell_bold(
            metadata_table.cell(
                row_index,
                0,
            ),
            True,
        )

    document.add_paragraph()

    # --------------------------------------------------------------
    # Executive summary
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "1. Executive Summary",
        level=1,
    )

    n_rows = len(dataset)
    n_columns = len(dataset.columns)

    numeric_columns = len(
        dataset.select_dtypes(
            include=[np.number]
        ).columns
    )

    missing_cells = int(
        dataset.isna().sum().sum()
    )

    duplicate_rows = int(
        dataset.duplicated().sum()
    )

    summary_table = pd.DataFrame(
        {
            "Metric": [
                "Observations",
                "Columns",
                "Numeric columns",
                "Engineered features",
                "Missing cells",
                "Duplicate rows",
            ],
            "Value": [
                n_rows,
                n_columns,
                numeric_columns,
                len(engineered_features),
                missing_cells,
                duplicate_rows,
            ],
        }
    )

    add_docx_table(
        document,
        summary_table,
        max_rows=20,
    )

    add_docx_callout(
        document,
        "Dataset interpretation",
        (
            "The AI4I 2020 dataset is synthetic. UID is treated as an "
            "identifier rather than being automatically interpreted as "
            "a genuine machine timestamp. Genuine temporal lag and "
            "rolling features require chronological observations."
        ),
    )

    # --------------------------------------------------------------
    # Dataset overview
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "2. Dataset Overview",
        level=1,
    )

    dataset_summary = prepare_dataset_summary(
        dataset,
        target_column=metadata.target_column,
    )

    add_docx_table(
        document,
        dataset_summary,
        max_rows=20,
    )

    paragraph = document.add_paragraph()

    paragraph.add_run(
        "Official dataset reference: "
    ).bold = True

    paragraph.add_run(
        metadata.dataset_url
    )

    # --------------------------------------------------------------
    # Methodology
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "3. Feature Engineering Methodology",
        level=1,
    )

    methodology = (
        methodology_notes
        if methodology_notes
        else [
            "Time-based features are generated only when a genuine timestamp exists.",
            "Lag features use previous observations only.",
            "Rolling statistics use historical windows and never future observations.",
            "Exponentially weighted statistics emphasize recent historical behavior.",
            "Sensor differences and ratios encode relationships between physical measurements.",
            "Temperature gap captures process-versus-air thermal behavior.",
            "Mechanical power combines torque and rotational speed.",
            "Tool-wear transformations represent degradation progression.",
            "Rate-of-change features capture dynamic sensor behavior.",
            "Z-score features quantify deviations from historical behavior.",
            "Operating-condition features describe machine state.",
            "Missing-value handling is designed to avoid future-data leakage.",
        ]
    )

    add_docx_bullet_list(
        document,
        methodology,
    )

    # --------------------------------------------------------------
    # Feature families
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "4. Feature Families",
        level=1,
    )

    feature_families = [
        "Time-based features",
        "Lag features",
        "Rolling mean",
        "Rolling standard deviation",
        "Rolling minimum and maximum",
        "Rolling median",
        "Exponentially weighted moving averages",
        "Sensor differences",
        "Sensor ratios",
        "Temperature gap",
        "Mechanical power",
        "Torque × rotational-speed interaction",
        "Tool-wear transformations",
        "Rate-of-change features",
        "Z-score / anomaly features",
        "Interaction features",
        "Machine operating-condition features",
        "Missing-value indicators and safe imputation",
        "Constant and duplicate feature diagnostics",
    ]

    add_docx_bullet_list(
        document,
        feature_families,
    )

    # --------------------------------------------------------------
    # Feature inventory
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "5. Feature Inventory",
        level=1,
    )

    inventory = prepare_feature_inventory(
        dataset,
        target_column=metadata.target_column,
    )

    add_docx_table(
        document,
        inventory,
        max_rows=config.max_feature_rows,
    )

    if engineered_features:

        add_docx_heading(
            document,
            "Generated Features",
            level=2,
        )

        for feature in engineered_features:

            paragraph = document.add_paragraph(
                style="List Bullet"
            )

            paragraph.add_run(
                feature
            ).bold = True

            description = (
                feature_descriptions.get(
                    feature
                )
            )

            if description:

                paragraph.add_run(
                    f" — {description}"
                )

    # --------------------------------------------------------------
    # Quality assessment
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "6. Feature Quality Assessment",
        level=1,
    )

    feature_statistics = quality_results.get(
        "feature_statistics",
        pd.DataFrame(),
    )

    if not feature_statistics.empty:

        add_docx_heading(
            document,
            "Feature Statistics",
            level=2,
        )

        add_docx_table(
            document,
            feature_statistics,
            max_rows=config.max_feature_rows,
        )

    missing_features = quality_results.get(
        "missing_features",
        pd.DataFrame(),
    )

    if not missing_features.empty:

        add_docx_heading(
            document,
            "Missing-Value Diagnostics",
            level=2,
        )

        add_docx_table(
            document,
            missing_features,
            max_rows=config.max_feature_rows,
        )

    duplicate_pairs = quality_results.get(
        "duplicate_feature_pairs",
        pd.DataFrame(),
    )

    if not duplicate_pairs.empty:

        add_docx_heading(
            document,
            "Duplicate Feature Pairs",
            level=2,
        )

        add_docx_table(
            document,
            duplicate_pairs,
            max_rows=config.max_feature_rows,
        )

    infinite_values = quality_results.get(
        "infinite_values",
        pd.DataFrame(),
    )

    if not infinite_values.empty:

        add_docx_heading(
            document,
            "Infinite-Value Diagnostics",
            level=2,
        )

        add_docx_table(
            document,
            infinite_values,
            max_rows=config.max_feature_rows,
        )

    recommendations = quality_results.get(
        "recommendations",
        pd.DataFrame(),
    )

    if not recommendations.empty:

        add_docx_heading(
            document,
            "Feature Recommendations",
            level=2,
        )

        add_docx_table(
            document,
            recommendations,
            max_rows=config.max_feature_rows,
        )

    # --------------------------------------------------------------
    # Correlation analysis
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "7. Correlation Analysis",
        level=1,
    )

    highly_correlated = quality_results.get(
        "highly_correlated_features",
        pd.DataFrame(),
    )

    if not highly_correlated.empty:

        add_docx_heading(
            document,
            "Highly Correlated Feature Pairs",
            level=2,
        )

        add_docx_table(
            document,
            highly_correlated,
            max_rows=config.max_correlation_pairs,
        )

    target_correlations = quality_results.get(
        "target_correlations",
        pd.DataFrame(),
    )

    if not target_correlations.empty:

        add_docx_heading(
            document,
            "Feature–Target Correlations",
            level=2,
        )

        add_docx_table(
            document,
            target_correlations,
            max_rows=config.max_target_correlations,
        )

    # --------------------------------------------------------------
    # Distribution diagnostics
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "8. Distribution and Outlier Diagnostics",
        level=1,
    )

    distribution_summary = quality_results.get(
        "distribution_summary",
        pd.DataFrame(),
    )

    if not distribution_summary.empty:

        add_docx_table(
            document,
            distribution_summary,
            max_rows=config.max_distribution_rows,
        )

    outlier_summary = quality_results.get(
        "outlier_summary",
        pd.DataFrame(),
    )

    if not outlier_summary.empty:

        add_docx_heading(
            document,
            "IQR Outlier Diagnostics",
            level=2,
        )

        add_docx_table(
            document,
            outlier_summary,
            max_rows=config.max_distribution_rows,
        )

    # --------------------------------------------------------------
    # Leakage prevention
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "9. Leakage Prevention",
        level=1,
    )

    leakage = (
        leakage_notes
        if leakage_notes
        else [
            "UID is not treated as a genuine timestamp in AI4I.",
            "Failure-mode labels are excluded from predictive sensor features.",
            "Lag and rolling calculations use only historical information.",
            "No future observations are used to construct past features.",
            "Learned preprocessing parameters are fitted using training data only.",
            "Feature selection decisions should be made using training data only.",
            "Validation and test sets use transformations learned from training data.",
        ]
    )

    add_docx_bullet_list(
        document,
        leakage,
    )

    leakage_report = quality_results.get(
        "leakage_report",
        pd.DataFrame(),
    )

    if not leakage_report.empty:

        add_docx_heading(
            document,
            "Potential Leakage Diagnostics",
            level=2,
        )

        add_docx_table(
            document,
            leakage_report,
            max_rows=config.max_feature_rows,
        )

    # --------------------------------------------------------------
    # Train/validation/test
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "10. Train / Validation / Test Compatibility",
        level=1,
    )

    split_rows = []

    for name, shape in [
        ("Training", train_shape),
        ("Validation", validation_shape),
        ("Test", test_shape),
    ]:

        if shape is None:
            continue

        split_rows.append(
            {
                "Split": name,
                "Rows": shape[0],
                "Columns": shape[1],
            }
        )

    if split_rows:

        add_docx_table(
            document,
            pd.DataFrame(split_rows),
            max_rows=10,
        )

    add_docx_callout(
        document,
        "Recommended practice",
        (
            "For genuine machine time-series data, chronological or "
            "machine-aware grouped splitting is preferred over naive "
            "random row splitting. The feature definitions must remain "
            "identical across training, validation and test datasets."
        ),
    )

    # --------------------------------------------------------------
    # Real-time processing
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "11. Real-Time / Online Feature Engineering",
        level=1,
    )

    realtime = (
        realtime_notes
        if realtime_notes
        else [
            "Maintain feature state separately for each machine.",
            "Only current and historical observations may influence the current feature vector.",
            "Rolling windows should be implemented with bounded state.",
            "Production and offline feature definitions must remain identical.",
            "Monitor missing sensors, impossible values and feature drift.",
            "The online feature generator should expose deterministic outputs for the same input state.",
        ]
    )

    add_docx_bullet_list(
        document,
        realtime,
    )

    # --------------------------------------------------------------
    # Figures
    # --------------------------------------------------------------

    if figures:

        add_docx_heading(
            document,
            "12. Visual Diagnostics",
            level=1,
        )

        for figure_name, figure_path in figures.items():

            add_docx_figure(
                document,
                figure_path,
                str(figure_name),
            )

    # --------------------------------------------------------------
    # Conclusion
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "13. Conclusions and Readiness",
        level=1,
    )

    add_docx_callout(
        document,
        "Task 2 readiness criteria",
        (
            "The feature-engineering stage is ready for downstream "
            "modeling when feature definitions are reproducible, "
            "temporal calculations are leakage-safe, learned "
            "transformations are fitted only on training data, "
            "feature quality issues are documented, and the same "
            "feature definitions can be reproduced in real-time."
        ),
    )

    # --------------------------------------------------------------
    # References
    # --------------------------------------------------------------

    add_docx_heading(
        document,
        "14. References",
        level=1,
    )

    references = [
        (
            "UCI Machine Learning Repository. "
            "AI4I 2020 Predictive Maintenance Dataset. "
            f"DOI: {metadata.dataset_doi}."
        ),
        (
            "Official dataset page: "
            f"{metadata.dataset_url}"
        ),
    ]

    add_docx_bullet_list(
        document,
        references,
    )

    # --------------------------------------------------------------
    # Save
    # --------------------------------------------------------------

    output_path = (
        output_directory
        / config.docx_filename
    )

    if (
        output_path.exists()
        and not config.overwrite_existing
    ):

        raise FileExistsError(
            f"Report already exists: {output_path}"
        )

    document.save(
        str(output_path)
    )

    return output_path


# ---------------------------------------------------------------------
# Combined report generation
# ---------------------------------------------------------------------

def generate_all_reports(
    *,
    metadata: Optional[
        ReportMetadata
    ] = None,
    config: Optional[
        ReportConfig
    ] = None,
    dataset: pd.DataFrame,
    quality_results: Optional[
        Mapping[str, pd.DataFrame]
    ] = None,
    engineered_features: Optional[
        Sequence[str]
    ] = None,
    feature_descriptions: Optional[
        Mapping[str, str]
    ] = None,
    figures: Optional[
        Mapping[str, str | Path]
    ] = None,
    train_shape: Optional[
        tuple[int, int]
    ] = None,
    validation_shape: Optional[
        tuple[int, int]
    ] = None,
    test_shape: Optional[
        tuple[int, int]
    ] = None,
    methodology_notes: Optional[
        Sequence[str]
    ] = None,
    leakage_notes: Optional[
        Sequence[str]
    ] = None,
    realtime_notes: Optional[
        Sequence[str]
    ] = None,
) -> dict[str, Path]:
    """
    Generate both HTML and DOCX reports.

    Returns
    -------
    dict[str, pathlib.Path]
        Generated report paths.
    """

    metadata = (
        metadata
        or ReportMetadata()
    )

    config = (
        config
        or ReportConfig()
    )

    generated: dict[str, Path] = {}

    html_path = generate_html_report(
        metadata=metadata,
        config=config,
        dataset=dataset,
        quality_results=quality_results,
        engineered_features=engineered_features,
        feature_descriptions=feature_descriptions,
        figures=figures,
        train_shape=train_shape,
        validation_shape=validation_shape,
        test_shape=test_shape,
        methodology_notes=methodology_notes,
        leakage_notes=leakage_notes,
        realtime_notes=realtime_notes,
    )

    generated[
        "html"
    ] = html_path

    if config.generate_docx:

        docx_path = generate_docx_report(
            metadata=metadata,
            config=config,
            dataset=dataset,
            quality_results=quality_results,
            engineered_features=engineered_features,
            feature_descriptions=feature_descriptions,
            figures=figures,
            train_shape=train_shape,
            validation_shape=validation_shape,
            test_shape=test_shape,
            methodology_notes=methodology_notes,
            leakage_notes=leakage_notes,
            realtime_notes=realtime_notes,
        )

        generated[
            "docx"
        ] = docx_path

    return generated


# ---------------------------------------------------------------------
# Save report manifest
# ---------------------------------------------------------------------

def save_report_manifest(
    generated_reports: Mapping[str, str | Path],
    *,
    output_path: str | Path = (
        "reports/report_manifest.json"
    ),
    metadata: Optional[
        ReportMetadata
    ] = None,
) -> Path:
    """
    Save a machine-readable report manifest.
    """

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    manifest = {
        "generated_at": datetime.now(
            timezone.utc
        ).isoformat(),
        "reports": {
            name: str(
                Path(path)
            )
            for name, path
            in generated_reports.items()
        },
    }

    if metadata is not None:

        manifest[
            "metadata"
        ] = {
            "project_name": metadata.project_name,
            "title": metadata.title,
            "dataset_name": metadata.dataset_name,
            "dataset_source": metadata.dataset_source,
            "dataset_doi": metadata.dataset_doi,
            "time_series_mode": metadata.time_series_mode,
            "timestamp_column": metadata.timestamp_column,
            "machine_id_column": metadata.machine_id_column,
            "target_column": metadata.target_column,
            "project_version": metadata.project_version,
        }

    output_path.write_text(
        json.dumps(
            manifest,
            indent=4,
        ),
        encoding="utf-8",
    )

    return output_path


# ---------------------------------------------------------------------
# Standalone demonstration
# ---------------------------------------------------------------------

if __name__ == "__main__":

    print("=" * 76)
    print(
        "Predictive Maintenance — Report Generator"
    )
    print("=" * 76)

    # --------------------------------------------------------------
    # Demonstration dataset
    # --------------------------------------------------------------

    rng = np.random.default_rng(
        42
    )

    n = 250

    demo_df = pd.DataFrame(
        {
            "uid": np.arange(
                1,
                n + 1,
            ),
            "air_temperature_k": (
                298
                + rng.normal(
                    0,
                    1.2,
                    n,
                )
            ),
            "process_temperature_k": (
                308
                + rng.normal(
                    0,
                    1.4,
                    n,
                )
            ),
            "rotational_speed_rpm": (
                1500
                + rng.normal(
                    0,
                    100,
                    n,
                )
            ),
            "torque_nm": (
                40
                + rng.normal(
                    0,
                    7,
                    n,
                )
            ),
            "tool_wear_min": np.arange(
                n
            ),
            "machine_failure": (
                rng.random(n)
                < 0.035
            ).astype(int),
        }
    )

    # --------------------------------------------------------------
    # Example engineered features
    # --------------------------------------------------------------

    demo_df[
        "temperature_gap_k"
    ] = (
        demo_df[
            "process_temperature_k"
        ]
        - demo_df[
            "air_temperature_k"
        ]
    )

    demo_df[
        "mechanical_power_w"
    ] = (
        demo_df[
            "torque_nm"
        ]
        * demo_df[
            "rotational_speed_rpm"
        ]
        * 2
        * np.pi
        / 60
    )

    demo_df[
        "torque_speed_interaction"
    ] = (
        demo_df[
            "torque_nm"
        ]
        * demo_df[
            "rotational_speed_rpm"
        ]
    )

    engineered_features = [
        "temperature_gap_k",
        "mechanical_power_w",
        "torque_speed_interaction",
    ]

    feature_descriptions = {
        "temperature_gap_k": (
            "Difference between process and air temperature."
        ),
        "mechanical_power_w": (
            "Mechanical power derived from torque and rotational speed."
        ),
        "torque_speed_interaction": (
            "Interaction between torque and rotational speed."
        ),
    }

    # --------------------------------------------------------------
    # Example quality results
    # --------------------------------------------------------------

    quality_results = {
        "feature_statistics": pd.DataFrame(
            {
                "feature": demo_df.columns,
                "missing_percentage": [
                    demo_df[c].isna().mean()
                    for c in demo_df.columns
                ],
                "unique_count": [
                    demo_df[c].nunique()
                    for c in demo_df.columns
                ],
            }
        ),
        "target_correlations": pd.DataFrame(
            {
                "feature": [
                    "mechanical_power_w",
                    "torque_speed_interaction",
                    "temperature_gap_k",
                ],
                "target": [
                    "machine_failure"
                ] * 3,
                "correlation": [
                    0.14,
                    0.13,
                    -0.04,
                ],
                "absolute_correlation": [
                    0.14,
                    0.13,
                    0.04,
                ],
            }
        ),
        "highly_correlated_features": (
            pd.DataFrame(
                columns=[
                    "feature_1",
                    "feature_2",
                    "correlation",
                    "absolute_correlation",
                ]
            )
        ),
        "missing_features": pd.DataFrame(),
        "duplicate_feature_pairs": pd.DataFrame(),
        "infinite_values": pd.DataFrame(),
        "distribution_summary": pd.DataFrame(),
        "outlier_summary": pd.DataFrame(),
        "leakage_report": pd.DataFrame(),
        "recommendations": pd.DataFrame(),
    }

    # --------------------------------------------------------------
    # Metadata
    # --------------------------------------------------------------

    metadata = ReportMetadata(
        project_name=DEFAULT_PROJECT_NAME,
        title=(
            "Task 2 — Feature Engineering "
            "Technical Report"
        ),
        dataset_name=UCI_DATASET_NAME,
        dataset_source=(
            "UCI Machine Learning Repository"
        ),
        dataset_reference=(
            "AI4I 2020 Predictive Maintenance Dataset"
        ),
        dataset_doi=UCI_DATASET_DOI,
        dataset_url=UCI_DATASET_URL,
        time_series_mode=(
            "AI4I/reference mode"
        ),
        target_column="machine_failure",
    )

    config = ReportConfig(
        output_directory="reports/demo",
        figures_directory="reports/figures/demo",
        generate_docx=True,
    )

    # --------------------------------------------------------------
    # Generate reports
    # --------------------------------------------------------------

    try:

        generated = generate_all_reports(
            metadata=metadata,
            config=config,
            dataset=demo_df,
            quality_results=quality_results,
            engineered_features=engineered_features,
            feature_descriptions=feature_descriptions,
            train_shape=(175, len(demo_df.columns)),
            validation_shape=(37, len(demo_df.columns)),
            test_shape=(38, len(demo_df.columns)),
            methodology_notes=[
                "Physical transformations are applied without fabricating timestamps.",
                "Temporal features are reserved for genuine chronological datasets.",
                "Derived power uses torque and rotational speed.",
                "Feature quality is assessed before downstream modeling.",
            ],
        )

        manifest_path = save_report_manifest(
            generated,
            output_path=(
                "reports/demo/"
                "report_manifest.json"
            ),
            metadata=metadata,
        )

        print(
            "\nGenerated reports:"
        )

        for name, path in generated.items():

            print(
                f"  {name}: {path}"
            )

        print(
            f"  manifest: {manifest_path}"
        )

    except ImportError as exc:

        print(
            "\nDOCX dependency is unavailable."
        )

        print(
            str(exc)
        )

        # Generate HTML even if python-docx is unavailable.
        html_config = ReportConfig(
            output_directory="reports/demo",
            figures_directory="reports/figures/demo",
            generate_docx=True,
        )

        html_path = generate_html_report(
            metadata=metadata,
            config=html_config,
            dataset=demo_df,
            quality_results=quality_results,
            engineered_features=engineered_features,
            feature_descriptions=feature_descriptions,
        )

        print(
            f"\nHTML report generated: {html_path}"
        )

    print(
        "\nReport generator module completed successfully."
    )
